{% set version = "1.14.0" %}
{% set name = "pepStat" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8e38350bee8eb0ebbaff0a1f3f7a1351a926593656b81dc64d6829d3523c3f4a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - r-base
    - r-data.table
    - r-fields
    - r-ggplot2
    - r-plyr
  run:
    - bioconductor-biobase
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - r-base
    - r-data.table
    - r-fields
    - r-ggplot2
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Statistical analysis of peptide microarrays'

