{% set version = "2.20.0" %}
{% set name = "ReportingTools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 78fbf2d6b98f7683f303c551de46ec75077b35459febebcb827286b391c57e6d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.6'
    - bioconductor-category
    - 'bioconductor-deseq2 >=1.3.41'
    - bioconductor-edger
    - bioconductor-ggbio
    - bioconductor-gostats
    - bioconductor-gseabase
    - bioconductor-iranges
    - 'bioconductor-limma >=3.17.5'
    - bioconductor-pfam.db
    - r-base
    - r-ggplot2
    - r-hwriter
    - r-knitr
    - r-lattice
    - r-r.utils
    - r-xml
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.6'
    - bioconductor-category
    - 'bioconductor-deseq2 >=1.3.41'
    - bioconductor-edger
    - bioconductor-ggbio
    - bioconductor-gostats
    - bioconductor-gseabase
    - bioconductor-iranges
    - 'bioconductor-limma >=3.17.5'
    - bioconductor-pfam.db
    - r-base
    - r-ggplot2
    - r-hwriter
    - r-knitr
    - r-lattice
    - r-r.utils
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'The ReportingTools software package enables users to easily display reports of analysis results generated from sources such as microarray and sequencing data.  The package allows users to create HTML pages that may be viewed on a web browser such as Safari, or in other formats readable by programs such as Excel.  Users can generate tables with sortable and filterable columns, make and display plots, and link table entries to other data sources such as NCBI or larger plots within the HTML page.  Using the package, users can also produce a table of contents page to link various reports together for a particular project that can be viewed in a web browser.  For more examples, please visit our site: http:// research-pub.gene.com/ReportingTools.'

