{% set version = "1.38.0" %}
{% set name = "ShortRead" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: cb058f83d68937dc1ec1d6662d2597c65bbdfc943a24ffe5bbab7085cf1f1f0d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.23.3'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicalignments >=1.15.6'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - bioconductor-xvector
    - bioconductor-zlibbioc
    - r-base
    - r-hwriter
    - r-lattice
    - r-latticeextra
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.23.3'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicalignments >=1.15.6'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - bioconductor-xvector
    - bioconductor-zlibbioc
    - r-base
    - r-hwriter
    - r-lattice
    - r-latticeextra
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package implements sampling, iteration, and input of FASTQ files. The package includes functions for filtering and trimming reads, and for generating a quality assessment report. Data are represented as DNAStringSet-derived objects, and easily manipulated for a diversity of purposes.  The package also contains legacy support for early single-end, ungapped alignment formats.'

