{% set version = "1.16.0" %}
{% set name = "DMRcate" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: aaa612d617c617b313aa6ffa4ef80c33efe3c5dcc36f573cc02442d18bfab04a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-dmrcatedata
    - bioconductor-dss
    - bioconductor-genomicranges
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-minfi
    - bioconductor-missmethyl
    - bioconductor-s4vectors
    - r-base
    - r-plyr
  run:
    - bioconductor-dmrcatedata
    - bioconductor-dss
    - bioconductor-genomicranges
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-minfi
    - bioconductor-missmethyl
    - bioconductor-s4vectors
    - r-base
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'file LICENSE'
  summary: 'De novo identification and extraction of differentially methylated regions (DMRs) from the human genome using Whole Genome Bisulphite Sequencing (WGBS) and Illumina Infinium Array (450K and EPIC) data. Provides functionality for filtering probes possibly confounded by SNPs and cross-hybridisation. Includes GRanges generation and plotting functions.'

