{% set version = "1.24.0" %}
{% set name = "ChIPXpress" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b64b509939b988973f09aaf715529d8a5e9eb84f83d2aefd88cc3ea633ae53a1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-chipxpressdata
    - bioconductor-frma
    - bioconductor-geoquery
    - r-base
    - r-biganalytics
    - r-bigmemory
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-chipxpressdata
    - bioconductor-frma
    - bioconductor-geoquery
    - r-base
    - r-biganalytics
    - r-bigmemory
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL(>=2)
  summary: 'ChIPXpress takes as input predicted TF bound genes from ChIPx data and uses a corresponding database of gene expression profiles downloaded from NCBI GEO to rank the TF bound targets in order of which gene is most likely to be functional TF target.'

