{% set version = "1.56.0" %}
{% set name = "affyPLM" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 94ca54deabc2b4be06f22e3a4c0a824336dd27853ea275701d2f69f4e66778a3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affy >=1.11.0'
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-gcrma
    - 'bioconductor-preprocesscore >=1.5.1'
    - bioconductor-zlibbioc
    - r-base
  run:
    - 'bioconductor-affy >=1.11.0'
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-gcrma
    - 'bioconductor-preprocesscore >=1.5.1'
    - bioconductor-zlibbioc
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'A package that extends and improves the functionality of the base affy package. Routines that make heavy use of compiled code for speed. Central focus is on implementation of methods for fitting probe-level models and tools using these models. PLM based quality assessment tools.'

