{% set version = "2.4.1" %}
{% set name = "ensembldb" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 86a3df73a98d820149084c5f0114d433e5533a6cc3914f7e2d60331f3b234bd0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.31.19'
    - 'bioconductor-annotationfilter >=1.1.9'
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.15.10'
    - 'bioconductor-biostrings >=2.47.9'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicfeatures >=1.29.10'
    - 'bioconductor-genomicranges >=1.31.18'
    - 'bioconductor-iranges >=2.13.24'
    - bioconductor-protgenerics
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - r-base
    - r-curl
    - r-dbi
    - 'r-rsqlite >=1.1'
  run:
    - 'bioconductor-annotationdbi >=1.31.19'
    - 'bioconductor-annotationfilter >=1.1.9'
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.15.10'
    - 'bioconductor-biostrings >=2.47.9'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicfeatures >=1.29.10'
    - 'bioconductor-genomicranges >=1.31.18'
    - 'bioconductor-iranges >=2.13.24'
    - bioconductor-protgenerics
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - r-base
    - r-curl
    - r-dbi
    - 'r-rsqlite >=1.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'The package provides functions to create and use transcript centric annotation databases/packages. The annotation for the databases are directly fetched from Ensembl using their Perl API. The functionality and data is similar to that of the TxDb packages from the GenomicFeatures package, but, in addition to retrieve all gene/transcript models and annotations from the database, ensembldb provides a filter framework allowing to retrieve annotations for specific entries like genes encoded on a chromosome region or transcript models of lincRNA genes. EnsDb databases built with ensembldb contain also protein annotations and mappings between proteins and their encoding transcripts. Finally, ensembldb provides functions to map between genomic, transcript and protein coordinates.'

