{% set version = "2.8.1" %}
{% set name = "rols" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 05cfb98881859d030c7655f8e41a7aeb70c14feeb5d8afb99d9b4c905a8a3143
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.23.1'
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.23.1'
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The rols package is an interface to the Ontology Lookup Service (OLS) to access and query hundred of ontolgies directly from R.'

