{% set version = "2.52.0" %}
{% set name = "gcrma" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: e1310d019392319f8d4384653deab6122d1db1c0d8594b8e10c874e7ba2f8291
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affy >=1.23.2'
    - 'bioconductor-affyio >=1.13.3'
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - 'bioconductor-biostrings >=2.11.32'
    - bioconductor-xvector
    - r-base
  run:
    - 'bioconductor-affy >=1.23.2'
    - 'bioconductor-affyio >=1.13.3'
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - 'bioconductor-biostrings >=2.11.32'
    - bioconductor-xvector
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'Background adjustment using sequence information'

