{% set version = "2.14.0" %}
{% set name = "casper" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ceada9d23d5da7e0f65bd6355722ba1d25f979318b0c7e0e0242149b44e68a37
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-ebarrays
    - bioconductor-gaga
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-coda
    - r-gtools
    - r-mgcv
    - r-sqldf
    - r-survival
    - r-vgam
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-ebarrays
    - bioconductor-gaga
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-coda
    - r-gtools
    - r-mgcv
    - r-sqldf
    - r-survival
    - r-vgam
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Infer alternative splicing from paired-end RNA-seq data. The model is based on counting paths across exons, rather than pairwise exon connections, and estimates the fragment size and start distributions non-parametrically, which improves estimation precision.'

