{% set version = "2.26.0" %}
{% set name = "ncdfFlow" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 4207f655bebb5b0186616730967db07b9e413f5448b2e3a943e79c2a0ce63f7d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-flowcore >=1.45.11'
    - bioconductor-flowviz
    - bioconductor-rhdf5lib
    - bioconductor-zlibbioc
    - r-base
    - r-bh
    - r-rcpp
    - r-rcpparmadillo
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-flowcore >=1.45.11'
    - bioconductor-flowviz
    - bioconductor-rhdf5lib
    - bioconductor-zlibbioc
    - r-base
    - r-bh
    - r-rcpp
    - r-rcpparmadillo
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Provides HDF5 storage based methods and functions for manipulation of flow cytometry data.'

