{% set version = "1.18.0" %}
{% set name = "prot2D" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 9b9fa1a7e5d6c16bbff19671330ef02eb9dc6e92daba1eb15ce3106a564d914b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-mulcom
    - bioconductor-qvalue
    - r-base
    - r-fdrtool
    - r-mass
    - r-samr
    - r-st
  run:
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-mulcom
    - bioconductor-qvalue
    - r-base
    - r-fdrtool
    - r-mass
    - r-samr
    - r-st
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'The purpose of this package is to analyze (i.e. Normalize and select significant spots) data issued from 2D GEl experiments'

