{% set version = "2.32.0" %}
{% set name = "lumi" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: d272815d5c876f5254f5388da3fd6fcff47d3467be2e0d881f41ad8a4769b419
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affy >=1.23.4'
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - 'bioconductor-methylumi >=2.3.2'
    - bioconductor-preprocesscore
    - r-base
    - r-dbi
    - r-kernsmooth
    - r-lattice
    - r-mass
    - 'r-mgcv >=1.4-0'
    - r-nleqslv
    - r-rsqlite
  run:
    - 'bioconductor-affy >=1.23.4'
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - 'bioconductor-methylumi >=2.3.2'
    - bioconductor-preprocesscore
    - r-base
    - r-dbi
    - r-kernsmooth
    - r-lattice
    - r-mass
    - 'r-mgcv >=1.4-0'
    - r-nleqslv
    - r-rsqlite
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'The lumi package provides an integrated solution for the Illumina microarray data analysis. It includes functions of Illumina BeadStudio (GenomeStudio) data input, quality control, BeadArray-specific variance stabilization, normalization and gene annotation at the probe level. It also includes the functions of processing Illumina methylation microarrays, especially Illumina Infinium methylation microarrays.'

