{% set version = "2.22.0" %}
{% set name = "SCAN.UPC" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 851c199a54f682a2faad4fe4311eb1c51e27d209ad64358f9afa5fcd193f1b5c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-affyio
    - 'bioconductor-biobase >=2.6.0'
    - bioconductor-biostrings
    - bioconductor-geoquery
    - bioconductor-iranges
    - bioconductor-oligo
    - bioconductor-sva
    - r-base
    - r-foreach
    - r-mass
  run:
    - bioconductor-affy
    - bioconductor-affyio
    - 'bioconductor-biobase >=2.6.0'
    - bioconductor-biostrings
    - bioconductor-geoquery
    - bioconductor-iranges
    - bioconductor-oligo
    - bioconductor-sva
    - r-base
    - r-foreach
    - r-mass
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: MIT
  summary: 'SCAN is a microarray normalization method to facilitate personalized-medicine workflows. Rather than processing microarray samples as groups, which can introduce biases and present logistical challenges, SCAN normalizes each sample individually by modeling and removing probe- and array-specific background noise using only data from within each array. SCAN can be applied to one-channel (e.g., Affymetrix) or two-channel (e.g., Agilent) microarrays. The Universal exPression Codes (UPC) method is an extension of SCAN that estimates whether a given gene/transcript is active above background levels in a given sample. The UPC method can be applied to one-channel or two-channel microarrays as well as to RNA-Seq read counts. Because UPC values are represented on the same scale and have an identical interpretation for each platform, they can be used for cross-platform data integration.'

