{% set version = "1.14.1" %}
{% set name = "csaw" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 718a6ce380ae8d7f72b1da2434705a459b373bb5fb1eb824823947949c6935ba
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocparallel
    - bioconductor-edger
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-zlibbioc
    - r-base
    - r-rcpp
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocparallel
    - bioconductor-edger
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-zlibbioc
    - r-base
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Detection of differentially bound regions in ChIP-seq data with sliding windows, with methods for normalization and proper FDR control.'

