{% set version = "2.10.0" %}
{% set name = "BubbleTree" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 966e8e59ae9ac9ae950faf6559eb395cd42d1853d12504bea1065308fffdd83c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-biocstyle
    - bioconductor-biovizbase
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - r-base
    - r-dplyr
    - r-e1071
    - r-ggplot2
    - r-gridextra
    - r-gtable
    - r-gtools
    - r-magrittr
    - r-plyr
    - r-rcolorbrewer
    - r-writexls
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-biocstyle
    - bioconductor-biovizbase
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - r-base
    - r-dplyr
    - r-e1071
    - r-ggplot2
    - r-gridextra
    - r-gtable
    - r-gtools
    - r-magrittr
    - r-plyr
    - r-rcolorbrewer
    - r-writexls
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 3)'
  summary: 'CNV analysis in groups of tumor samples.'

