{% set version = "1.12.0" %}
{% set name = "RNAprobR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 9e5e217ccb0af15db7a1994ff74ab2f4ed76233e8d6842178f03d383571a1934
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.10.0'
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-genomicalignments >=1.5.12'
    - 'bioconductor-genomicfeatures >=1.16.3'
    - 'bioconductor-genomicranges >=1.16.4'
    - 'bioconductor-iranges >=2.10.5'
    - 'bioconductor-rsamtools >=1.16.1'
    - 'bioconductor-rtracklayer >=1.24.2'
    - 'bioconductor-s4vectors >=0.14.7'
    - r-base
    - 'r-plyr >=1.8.1'
  run:
    - 'bioconductor-biocgenerics >=0.10.0'
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-genomicalignments >=1.5.12'
    - 'bioconductor-genomicfeatures >=1.16.3'
    - 'bioconductor-genomicranges >=1.16.4'
    - 'bioconductor-iranges >=2.10.5'
    - 'bioconductor-rsamtools >=1.16.1'
    - 'bioconductor-rtracklayer >=1.24.2'
    - 'bioconductor-s4vectors >=0.14.7'
    - r-base
    - 'r-plyr >=1.8.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'This package facilitates analysis of Next Generation Sequencing data for which positional information with a single nucleotide resolution is a key. It allows for applying different types of relevant normalizations, data visualization and export in a table or UCSC compatible bedgraph file.'

