{% set version = "1.10.2" %}
{% set name = "AnnotationHubData" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 4e18e50a99aefa9b9e2fc8c6a37659675a5bde5af8884c3b23360e2d4b4105c6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-annotationforge
    - 'bioconductor-annotationhub >=2.9.14'
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocinstaller
    - bioconductor-biocviews
    - bioconductor-biostrings
    - 'bioconductor-genomeinfodb >=1.15.4'
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-geoquery
    - 'bioconductor-iranges >=2.3.23'
    - bioconductor-organismdbi
    - bioconductor-rbiopaxparser
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.7.21'
    - r-base
    - r-dbi
    - 'r-futile.logger >=1.3.0'
    - r-jsonlite
    - r-rcurl
    - r-rsqlite
    - r-xml
  run:
    - bioconductor-annotationdbi
    - bioconductor-annotationforge
    - 'bioconductor-annotationhub >=2.9.14'
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocinstaller
    - bioconductor-biocviews
    - bioconductor-biostrings
    - 'bioconductor-genomeinfodb >=1.15.4'
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-geoquery
    - 'bioconductor-iranges >=2.3.23'
    - bioconductor-organismdbi
    - bioconductor-rbiopaxparser
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.7.21'
    - r-base
    - r-dbi
    - 'r-futile.logger >=1.3.0'
    - r-jsonlite
    - r-rcurl
    - r-rsqlite
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'These recipes convert a wide variety and a growing number of public bioinformatic data sets into easily-used standard Bioconductor data structures.'

