{% set version = "1.22.0" %}
{% set name = "VariantTools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 945d1d7f611094b7cfebf46583ebe431b644af071c385be5481e2cc8e78570f4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicfeatures >=1.31.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.33'
    - 'bioconductor-variantannotation >=1.11.16'
    - r-base
    - r-matrix
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicfeatures >=1.31.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.33'
    - 'bioconductor-variantannotation >=1.11.16'
    - r-base
    - r-matrix
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Explore, diagnose, and compare variant calls using filters.'

