{% set version = "1.20.1" %}
{% set name = "piano" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 11e0122d1189add38471fb1525f43b66a118512c687cb84acbfb55f4c797acdf
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-fgsea
    - bioconductor-marray
    - r-base
    - r-gplots
    - r-igraph
    - r-relations
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-fgsea
    - bioconductor-marray
    - r-base
    - r-gplots
    - r-igraph
    - r-relations
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Piano performs gene set analysis using various statistical methods, from different gene level statistics and a wide range of gene-set collections. Furthermore, the Piano package contains functions for combining the results of multiple runs of gene set analyses.'

