{% set version = "1.8.0" %}
{% set name = "SMITE" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8330f34bffd4221b8a60a0ea53604a8cbce6d0451588d324dfa14e2760e88947
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-bionet
    - bioconductor-genelendatabase
    - bioconductor-genomicranges
    - bioconductor-goseq
    - bioconductor-iranges
    - bioconductor-kegg.db
    - bioconductor-org.hs.eg.db
    - bioconductor-reactome.db
    - bioconductor-s4vectors
    - r-base
    - r-ggplot2
    - r-hmisc
    - r-igraph
    - r-plyr
    - r-scales
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-bionet
    - bioconductor-genelendatabase
    - bioconductor-genomicranges
    - bioconductor-goseq
    - bioconductor-iranges
    - bioconductor-kegg.db
    - bioconductor-org.hs.eg.db
    - bioconductor-reactome.db
    - bioconductor-s4vectors
    - r-base
    - r-ggplot2
    - r-hmisc
    - r-igraph
    - r-plyr
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'This package builds on the Epimods framework which facilitates finding weighted subnetworks ("modules") on Illumina Infinium 27k arrays using the SpinGlass algorithm, as implemented in the iGraph package. We have created a class of gene centric annotations associated with p-values and effect sizes and scores from any researchers prior statistical results to find functional modules.'

