{% set version = "1.8.0" %}
{% set name = "recoup" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 0aec44ef2f910c4d1d77709d551b9605e7f715f8e9649391e224ceb2e564a541
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-complexheatmap
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-rtracklayer
    - r-base
    - r-circlize
    - r-ggplot2
    - r-plyr
  run:
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-complexheatmap
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-rtracklayer
    - r-base
    - r-circlize
    - r-ggplot2
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'recoup calculates and plots signal profiles created from short sequence reads derived from Next Generation Sequencing technologies. The profiles provided are either sumarized curve profiles or heatmap profiles. Currently, recoup supports genomic profile plots for reads derived from ChIP-Seq and RNA-Seq experiments. The package uses ggplot2 and ComplexHeatmap graphics facilities for curve and heatmap coverage profiles respectively.'

