{% set version = "1.6.2" %}
{% set name = "chimeraviz" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 72155e7a9e6ae51f6ad588d6ee0d98cbcda3710d9794eb6c6f03d3d502f1d5a9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-annotationfilter
    - bioconductor-biocstyle
    - bioconductor-biostrings
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-rgraphviz
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - r-argumentcheck
    - r-base
    - r-data.table
    - r-dplyr
    - r-dt
    - r-plyr
    - r-rcircos
    - r-rcolorbrewer
    - r-rmarkdown
  run:
    - bioconductor-annotationdbi
    - bioconductor-annotationfilter
    - bioconductor-biocstyle
    - bioconductor-biostrings
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-rgraphviz
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - r-argumentcheck
    - r-base
    - r-data.table
    - r-dplyr
    - r-dt
    - r-plyr
    - r-rcircos
    - r-rcolorbrewer
    - r-rmarkdown
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'chimeraviz manages data from fusion gene finders and provides useful visualization tools.'

