{% set version = "1.24.0" %}
{% set name = "TransView" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 49007bacd52ae273fa3216f399b9e32e3d2441c44011b2b8600a96b8a2da48a5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.19.38'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-zlibbioc
    - r-base
    - r-gplots
  run:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.19.38'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-zlibbioc
    - r-base
    - r-gplots
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package provides efficient tools to generate, access and display read densities of sequencing based data sets such as from RNA-Seq and ChIP-Seq.'

