{% set version = "1.32.2" %}
{% set name = "GenomicFeatures" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ae6041a881ab060b3de153b7171d7a79f4453e0854a9dca1c0d3a115c3f3de4d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.41.4'
    - 'bioconductor-biobase >=2.15.1'
    - 'bioconductor-biocgenerics >=0.1.0'
    - 'bioconductor-biomart >=2.17.1'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.4'
    - 'bioconductor-genomicranges >=1.31.17'
    - 'bioconductor-iranges >=2.13.23'
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.29'
    - 'bioconductor-xvector >=0.19.7'
    - r-base
    - r-dbi
    - r-rcurl
    - 'r-rsqlite >=2.0'
  run:
    - 'bioconductor-annotationdbi >=1.41.4'
    - 'bioconductor-biobase >=2.15.1'
    - 'bioconductor-biocgenerics >=0.1.0'
    - 'bioconductor-biomart >=2.17.1'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.4'
    - 'bioconductor-genomicranges >=1.31.17'
    - 'bioconductor-iranges >=2.13.23'
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.29'
    - 'bioconductor-xvector >=0.19.7'
    - r-base
    - r-dbi
    - r-rcurl
    - 'r-rsqlite >=2.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'A set of tools and methods for making and manipulating transcript centric annotations. With these tools the user can easily download the genomic locations of the transcripts, exons and cds of a given organism, from either the UCSC Genome Browser or a BioMart database (more sources will be supported in the future). This information is then stored in a local database that keeps track of the relationship between transcripts, exons, cds and genes. Flexible methods are provided for extracting the desired features in a convenient format.'

