{% set version = "1.4.1" %}
{% set name = "IntEREst" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: cb2ebcacbd951c029c9ceb32360baa9dda9109d95eeed94b5d38ac4b52e56754
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-deseq2
    - bioconductor-dexseq
    - bioconductor-edger
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-seqlogo
    - bioconductor-summarizedexperiment
    - r-base
    - r-dbi
    - r-rmysql
    - r-seqinr
  run:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-deseq2
    - bioconductor-dexseq
    - bioconductor-edger
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-seqlogo
    - bioconductor-summarizedexperiment
    - r-base
    - r-dbi
    - r-rmysql
    - r-seqinr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package performs Intron-Exon Retention analysis on RNA-seq data (.bam files).'

