{% set version = "1.22.0" %}
{% set name = "annmap" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 60b56b634842ceafdbb54aa6d89e00fd082ad93a96d0793544fb7e53e14031af
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genefilter
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - r-base
    - r-dbi
    - r-digest
    - r-lattice
    - 'r-rmysql >=0.6-0'
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genefilter
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - r-base
    - r-dbi
    - r-digest
    - r-lattice
    - 'r-rmysql >=0.6-0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'annmap provides annotation mappings for Affymetrix exon arrays and coordinate based queries to support deep sequencing data analysis. Database access is hidden behind the API which provides a set of functions such as genesInRange(), geneToExon(), exonDetails(), etc. Functions to plot gene architecture and BAM file data are also provided. Underlying data are from Ensembl.'

