{% set version = "1.30.8" %}
{% set name = "Rsubread" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ea984b97e9762ff84879567c24d7cdd2d76eb77f27a69aa83ad1a4bb395b6d7a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - r-base
  run:
    - r-base
  build:
    - {{ compiler('c') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Rsubread is a toolbox developed for the analyses of second and third generation sequencing data. It can be used for read mapping, read counting, SNP calling, structural variant detection and gene fusion discovery. It can be applied to all major sequencing techologies and it is suitable for the analysis of both short and long reads.'

