{% set version = "1.32.0" %}
{% set name = "girafe" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 18090a1f196e19f69fdb4ec9404a8e54bc5c8613ed6bb5d5047413ebe330d4b2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.8'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeintervals >=1.25.1'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-shortread >=1.37.1'
    - r-base
    - 'r-intervals >=0.13.1'
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.8'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeintervals >=1.25.1'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-shortread >=1.37.1'
    - r-base
    - 'r-intervals >=0.13.1'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'The package ''girafe'' deals with the genome-level representation of aligned reads from next-generation sequencing data. It contains an object class for enabling a detailed description of genome intervals with aligned reads and functions for comparing, visualising, exporting and working with such intervals and the aligned reads. As such, the package interacts with and provides a link between the packages ShortRead, IRanges and genomeIntervals.'

