{% set version = "2.14.0" %}
{% set name = "qpgraph" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 8ece88886836fcb2693e43cee82a18c277b53548e40a716b3abc49d78fb3827e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocparallel
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - 'bioconductor-graph >=1.45.1'
    - bioconductor-iranges
    - bioconductor-rgraphviz
    - bioconductor-s4vectors
    - r-base
    - 'r-matrix >=1.0'
    - r-mvtnorm
    - r-qtl
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocparallel
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - 'bioconductor-graph >=1.45.1'
    - bioconductor-iranges
    - bioconductor-rgraphviz
    - bioconductor-s4vectors
    - r-base
    - 'r-matrix >=1.0'
    - r-mvtnorm
    - r-qtl
  build:
    - {{ compiler('c') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Estimate gene and eQTL networks from high-throughput expression and genotyping assays.'

