{% set version = "1.42.4" %}
{% set name = "VanillaICE" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 0f744caf4e2dcceb4d25dccfcf06147e479db8145289c27eb204a73893fb3763
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.6'
    - bioconductor-bsgenome.hsapiens.ucsc.hg18
    - bioconductor-crlmm
    - 'bioconductor-genomeinfodb >=1.11.4'
    - 'bioconductor-genomicranges >=1.27.6'
    - 'bioconductor-iranges >=1.14.0'
    - 'bioconductor-oligoclasses >=1.31.1'
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-summarizedexperiment >=1.5.3'
    - r-base
    - r-data.table
    - r-foreach
    - r-lattice
    - r-matrixstats
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.6'
    - bioconductor-bsgenome.hsapiens.ucsc.hg18
    - bioconductor-crlmm
    - 'bioconductor-genomeinfodb >=1.11.4'
    - 'bioconductor-genomicranges >=1.27.6'
    - 'bioconductor-iranges >=1.14.0'
    - 'bioconductor-oligoclasses >=1.31.1'
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-summarizedexperiment >=1.5.3'
    - r-base
    - r-data.table
    - r-foreach
    - r-lattice
    - r-matrixstats
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL-2
  summary: 'Hidden Markov Models for characterizing chromosomal alterations in high throughput SNP arrays.'

