{% set version = "2.12.0" %}
{% set name = "ballgown" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 782a9760d27bb529238b1ecd3fa2f2c0f364ba8f861d7fad54bd127e2935a6d2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=2.25.0'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.17.25'
    - 'bioconductor-iranges >=1.99.22'
    - bioconductor-limma
    - 'bioconductor-rtracklayer >=1.29.25'
    - 'bioconductor-s4vectors >=0.9.39'
    - bioconductor-sva
    - r-base
    - r-rcolorbrewer
  run:
    - 'bioconductor-biobase >=2.25.0'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.17.25'
    - 'bioconductor-iranges >=1.99.22'
    - bioconductor-limma
    - 'bioconductor-rtracklayer >=1.29.25'
    - 'bioconductor-s4vectors >=0.9.39'
    - bioconductor-sva
    - r-base
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Tools for statistical analysis of assembled transcriptomes, including flexible differential expression analysis, visualization of transcript structures, and matching of assembled transcripts to annotation.'

