{% set version = "1.8.0" %}
{% set name = "isomiRs" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a3144607ec7b762f47ffca04c00208ddca725eb5e4bb741ae98cc48da4e6f649
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-deseq2
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-targetscan.hs.eg.db
    - r-assertive.sets
    - r-base
    - r-discriminer
    - r-dplyr
    - r-ggally
    - r-ggplot2
    - r-gplots
    - r-gridextra
    - r-gtools
    - r-rcolorbrewer
    - r-readr
    - r-reshape
    - r-rlang
    - r-tibble
    - r-tidyr
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-deseq2
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-targetscan.hs.eg.db
    - r-assertive.sets
    - r-base
    - r-discriminer
    - r-dplyr
    - r-ggally
    - r-ggplot2
    - r-gplots
    - r-gridextra
    - r-gtools
    - r-rcolorbrewer
    - r-readr
    - r-reshape
    - r-rlang
    - r-tibble
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Characterization of miRNAs and isomiRs, clustering and differential expression.'

