{% set version = "1.22.0" %}
{% set name = "waveTiling" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 771257e7925bf8ae57b042f6885eb251184c285149d81e9c374fed49bdf82fb1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-biostrings
    - bioconductor-genomegraphs
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-oligo
    - bioconductor-oligoclasses
    - bioconductor-preprocesscore
    - r-base
    - r-waveslim
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-biostrings
    - bioconductor-genomegraphs
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-oligo
    - bioconductor-oligoclasses
    - bioconductor-preprocesscore
    - r-base
    - r-waveslim
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'This package is designed to conduct transcriptome analysis for tiling arrays based on fast wavelet-based functional models.'

