{% set version = "1.6.1" %}
{% set name = "PathoStat" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 2a097c072861423bcf6e498d6a10a2c847ace11a464f45ecbc702de9352410d3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocstyle
    - bioconductor-complexheatmap
    - bioconductor-deseq2
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-phyloseq
    - r-ape
    - r-base
    - r-corpcor
    - r-devtools
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-glmnet
    - r-gmodels
    - r-knitr
    - r-matrixstats
    - r-plotly
    - r-plyr
    - r-rcolorbrewer
    - r-rentrez
    - r-reshape2
    - r-rocr
    - r-scales
    - r-shiny
    - r-shinyjs
    - r-tidyr
    - r-vegan
    - r-webshot
    - r-xml
  run:
    - bioconductor-biocstyle
    - bioconductor-complexheatmap
    - bioconductor-deseq2
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-phyloseq
    - r-ape
    - r-base
    - r-corpcor
    - r-devtools
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-glmnet
    - r-gmodels
    - r-knitr
    - r-matrixstats
    - r-plotly
    - r-plyr
    - r-rcolorbrewer
    - r-rentrez
    - r-reshape2
    - r-rocr
    - r-scales
    - r-shiny
    - r-shinyjs
    - r-tidyr
    - r-vegan
    - r-webshot
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'The purpose of this package is to perform Statistical Microbiome Analysis on metagenomics results from sequencing data samples. In particular, it supports analyses on the PathoScope generated report files. PathoStat provides various functionalities including Relative Abundance charts, Diversity estimates and plots, tests of Differential Abundance, Time Series visualization, and Core OTU analysis.'

