{% set version = "1.42.1" %}
{% set name = "AnnotationDbi" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 2c2ce448f8512e9b9247dc1f1e2e8da6f53c7e8637e52bb200782310e95fd329
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=1.17.0'
    - 'bioconductor-biocgenerics >=0.23.1'
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-dbi
    - r-rsqlite
  run:
    - 'bioconductor-biobase >=1.17.0'
    - 'bioconductor-biocgenerics >=0.23.1'
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-dbi
    - r-rsqlite
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Provides user interface and database connection code for annotation data packages using SQLite data storage.'

