{% set version = "1.12.1" %}
{% set name = "GenVisR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 575d7f8a0c316661b6ff290c36a37006e62c20f1393675e85f93b86a1327b7b4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.25.4'
    - 'bioconductor-iranges >=2.7.5'
    - bioconductor-rsamtools
    - bioconductor-variantannotation
    - r-base
    - r-data.table
    - r-dbi
    - r-ffield
    - 'r-ggplot2 >=2.1.0'
    - 'r-gridextra >=2.0.0'
    - r-gtable
    - r-gtools
    - 'r-plyr >=1.8.3'
    - r-reshape2
    - r-scales
    - r-viridis
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.25.4'
    - 'bioconductor-iranges >=2.7.5'
    - bioconductor-rsamtools
    - bioconductor-variantannotation
    - r-base
    - r-data.table
    - r-dbi
    - r-ffield
    - 'r-ggplot2 >=2.1.0'
    - 'r-gridextra >=2.0.0'
    - r-gtable
    - r-gtools
    - 'r-plyr >=1.8.3'
    - r-reshape2
    - r-scales
    - r-viridis
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL-3 + file LICENSE'
  summary: 'Produce highly customizable publication quality graphics for genomic data primarily at the cohort level.'

