{% set version = "1.12.0" %}
{% set name = "CODEX" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: facca69dfd7a7bf32333eab374c82dac6178da13408a19cfcbc3dd0a0c02c65b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-genomeinfodb
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - r-base
  run:
    - bioconductor-biostrings
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-genomeinfodb
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'A normalization and copy number variation calling procedure for whole exome DNA sequencing data. CODEX relies on the availability of multiple samples processed using the same sequencing pipeline for normalization, and does not require matched controls. The normalization model in CODEX includes terms that specifically remove biases due to GC content, exon length and targeting and amplification efficiency, and latent systemic artifacts. CODEX also includes a Poisson likelihood-based recursive segmentation procedure that explicitly models the count-based exome sequencing data.'

