{% set version = "1.36.0" %}
{% set name = "genoset" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 6313ba101617a192ffc7066b3fccf4b564760f918838c5b53cb53e3faf3d33b8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.11.3'
    - 'bioconductor-genomeinfodb >=1.1.3'
    - 'bioconductor-genomicranges >=1.17.19'
    - 'bioconductor-iranges >=2.5.12'
    - 'bioconductor-s4vectors >=0.13.13'
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.11.3'
    - 'bioconductor-genomeinfodb >=1.1.3'
    - 'bioconductor-genomicranges >=1.17.19'
    - 'bioconductor-iranges >=2.5.12'
    - 'bioconductor-s4vectors >=0.13.13'
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'GenoSet provides an extension of the RangedSummarizedExperiment class with additional API features. This class provides convenient and fast methods for working with segmented genomic data. Additionally, GenoSet provides the class RleDataFrame which stores runs of data along the genome for multiple samples and provides very fast summaries of arbitrary row sets (regions of the genome).'

