{% set version = "1.42.0" %}
{% set name = "GSEABase" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ead00709a662c67665f4c176df3b32789118ce3269cb730c4e69ccb8b5487b85
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotate >=1.45.3'
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.13.8'
    - 'bioconductor-graph >=1.37.2'
    - r-base
    - r-xml
  run:
    - 'bioconductor-annotate >=1.45.3'
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.13.8'
    - 'bioconductor-graph >=1.37.2'
    - r-base
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package provides classes and methods to support Gene Set Enrichment Analysis (GSEA).'

