{% set version = "1.48.0" %}
{% set name = "BSgenome" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e815eb2def62b70e9aade10094f0cee3d9d3c44179581a4a9bf7b68271bc62e6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.13.8'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicranges >=1.31.10'
    - 'bioconductor-iranges >=2.13.16'
    - bioconductor-rsamtools
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.28'
    - bioconductor-xvector
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.13.8'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicranges >=1.31.10'
    - 'bioconductor-iranges >=2.13.16'
    - bioconductor-rsamtools
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.28'
    - bioconductor-xvector
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Infrastructure shared by all the Biostrings-based genome data packages.'

