{% set version = "1.4.3" %}
{% set name = "splatter" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5f163d95e7e1e143c7ad453bbe21e04903cc783a87aa1547e35ac9583ee558a2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-edger
    - 'bioconductor-scater >=1.7.4'
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-akima
    - r-base
    - r-checkmate
    - r-crayon
    - r-fitdistrplus
    - r-ggplot2
    - r-locfit
    - r-matrixstats
    - r-scales
  run:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-edger
    - 'bioconductor-scater >=1.7.4'
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-akima
    - r-base
    - r-checkmate
    - r-crayon
    - r-fitdistrplus
    - r-ggplot2
    - r-locfit
    - r-matrixstats
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL-3 + file LICENSE'
  summary: 'Splatter is a package for the simulation of single-cell RNA sequencing count data. It provides a simple interface for creating complex simulations that are reproducible and well-documented. Parameters can be estimated from real data and functions are provided for comparing real and simulated datasets.'

