{% set version = "1.6.0" %}
{% set name = "yarn" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 10760732a1437ca8e94773e452fbc49ed96a44ac6ff1a5c71b0e751136b39e3b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biomart
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-quantro
    - r-base
    - r-downloader
    - r-gplots
    - r-matrixstats
    - r-rcolorbrewer
    - r-readr
  run:
    - bioconductor-biobase
    - bioconductor-biomart
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-quantro
    - r-base
    - r-downloader
    - r-gplots
    - r-matrixstats
    - r-rcolorbrewer
    - r-readr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Expedite large RNA-Seq analyses using a combination of previously developed tools. YARN is meant to make it easier for the user in performing basic mis-annotation quality control, filtering, and condition-aware normalization. YARN leverages many Bioconductor tools and statistical techniques to account for the large heterogeneity and sparsity found in very large RNA-seq experiments.'

