{% set version = "1.4.0" %}
{% set name = "ideal" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: c5f3d116a78fc815cd99dd4b7b7640b0b7db3ad046cc26b92de3d75319aabc77
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocparallel
    - bioconductor-deseq2
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-goseq
    - bioconductor-gostats
    - bioconductor-ihw
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-pcaexplorer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-topgo
    - r-base
    - r-d3heatmap
    - r-dplyr
    - r-dt
    - 'r-ggplot2 >=2.0.0'
    - r-gplots
    - r-knitr
    - r-pheatmap
    - r-plyr
    - r-rentrez
    - r-rintrojs
    - r-rmarkdown
    - 'r-shiny >=0.12.0'
    - r-shinyace
    - r-shinybs
    - r-shinydashboard
    - r-stringr
    - r-upsetr
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocparallel
    - bioconductor-deseq2
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-goseq
    - bioconductor-gostats
    - bioconductor-ihw
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-pcaexplorer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-topgo
    - r-base
    - r-d3heatmap
    - r-dplyr
    - r-dt
    - 'r-ggplot2 >=2.0.0'
    - r-gplots
    - r-knitr
    - r-pheatmap
    - r-plyr
    - r-rentrez
    - r-rintrojs
    - r-rmarkdown
    - 'r-shiny >=0.12.0'
    - r-shinyace
    - r-shinybs
    - r-shinydashboard
    - r-stringr
    - r-upsetr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'This package provides functions for an Interactive Differential Expression AnaLysis of RNA-sequencing datasets, to extract quickly and effectively information downstream the step of differential expression. A Shiny application encapsulates the whole package.'

