{% set version = "1.44.0" %}
{% set name = "pdInfoBuilder" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 96f94b99e7db9a2a38dfa19cc518c87fddc465aeb654b5033933959914bcb172
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affxparser >=1.39.4'
    - 'bioconductor-biobase >=2.27.3'
    - 'bioconductor-biocgenerics >=0.13.11'
    - 'bioconductor-biostrings >=2.35.12'
    - 'bioconductor-iranges >=2.1.43'
    - 'bioconductor-oligo >=1.31.5'
    - 'bioconductor-oligoclasses >=1.29.6'
    - 'bioconductor-s4vectors >=0.5.22'
    - r-base
    - 'r-dbi >=0.3.1'
    - 'r-rsqlite >=1.0.0'
  run:
    - 'bioconductor-affxparser >=1.39.4'
    - 'bioconductor-biobase >=2.27.3'
    - 'bioconductor-biocgenerics >=0.13.11'
    - 'bioconductor-biostrings >=2.35.12'
    - 'bioconductor-iranges >=2.1.43'
    - 'bioconductor-oligo >=1.31.5'
    - 'bioconductor-oligoclasses >=1.29.6'
    - 'bioconductor-s4vectors >=0.5.22'
    - r-base
    - 'r-dbi >=0.3.1'
    - 'r-rsqlite >=1.0.0'
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Builds platform design information packages. These consist of a SQLite database containing feature-level data such as x, y position on chip and featureSet ID. The database also incorporates featureSet-level annotation data. The products of this packages are used by the oligo pkg.'

