{% set version = "1.6.0" %}
{% set name = "crisprseekplus" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ef0a05e770b745512ace4e0b3c56aae299cde00372490ecc75fbf86d674608e0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocinstaller
    - bioconductor-bsgenome
    - bioconductor-crisprseek
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-guideseq
    - r-base
    - r-dt
    - r-hash
    - r-shiny
    - r-shinyjs
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocinstaller
    - bioconductor-bsgenome
    - bioconductor-crisprseek
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-guideseq
    - r-base
    - r-dt
    - r-hash
    - r-shiny
    - r-shinyjs
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL-3 + file LICENSE'
  summary: 'Bioinformatics platform containing interface to work with offTargetAnalysis and compare2Sequences in the CRISPRseek package, and GUIDEseqAnalysis.'

