{% set version = "3.2.0" %}
{% set name = "xcms" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: af86ad398169f2ed955bb5fbfea86ca3913fda3431cbaac59ec0ca7b99e91a77
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-biocparallel >=1.8.0'
    - 'bioconductor-massspecwavelet >=1.5.2'
    - 'bioconductor-msnbase >=2.5.10'
    - bioconductor-multtest
    - 'bioconductor-mzr >=2.13.1'
    - bioconductor-protgenerics
    - bioconductor-s4vectors
    - r-base
    - r-lattice
    - r-plyr
    - r-rann
    - r-rcolorbrewer
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-biocparallel >=1.8.0'
    - 'bioconductor-massspecwavelet >=1.5.2'
    - 'bioconductor-msnbase >=2.5.10'
    - bioconductor-multtest
    - 'bioconductor-mzr >=2.13.1'
    - bioconductor-protgenerics
    - bioconductor-s4vectors
    - r-base
    - r-lattice
    - r-plyr
    - r-rann
    - r-rcolorbrewer
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2) + file LICENSE'
  summary: 'Framework for processing and visualization of chromatographically separated and single-spectra mass spectral data. Imports from AIA/ANDI NetCDF, mzXML, mzData and mzML files. Preprocesses data for high-throughput, untargeted analyte profiling.'

