{% set version = "1.48.0" %}
{% set name = "pathRender" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 329a09681d89938ae629526b3e80766af254482844a0e9e1d92d6144199607ee
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-cmap
    - bioconductor-graph
    - bioconductor-rgraphviz
    - r-base
    - r-rcolorbrewer
  run:
    - bioconductor-annotationdbi
    - bioconductor-cmap
    - bioconductor-graph
    - bioconductor-rgraphviz
    - r-base
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'build graphs from pathway databases, render them by Rgraphviz.'

