{% set version = "1.16.0" %}
{% set name = "GOTHiC" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: dfeeed7502bc4339e3da803968eb00a37e917945a283ec39935dedbcb20d36be
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.38'
    - bioconductor-shortread
    - r-base
    - r-data.table
    - r-ggplot2
  run:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.38'
    - bioconductor-shortread
    - r-base
    - r-data.table
    - r-ggplot2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This is a Hi-C analysis package using a cumulative binomial test to detect interactions between distal genomic loci that have significantly more reads than expected by chance in Hi-C experiments. It takes mapped paired NGS reads as input and gives back the list of significant interactions for a given bin size in the genome.'

