{% set version = "1.36.0" %}
{% set name = "RPA" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b3b9d728cf632bbc752e6b44e3cd63096edf718024c0e00b504d592f51f93050
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-biocgenerics
    - bioconductor-phyloseq
    - r-base
  run:
    - bioconductor-affy
    - bioconductor-biocgenerics
    - bioconductor-phyloseq
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'BSD_2_clause + file LICENSE'
  summary: 'Probabilistic analysis of probe reliability and differential gene expression on short oligonucleotide arrays.'

