{% set version = "1.48.0" %}
{% set name = "codelink" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 3455f089ce1063d6882a766752ee007a7e062082c77003155393073342338a4c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-limma
    - r-base
  run:
    - bioconductor-annotate
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-limma
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package facilitates reading, preprocessing and manipulating Codelink microarray data. The raw data must be exported as text file using the Codelink software.'

