{% set version = "1.8.4" %}
{% set name = "scater" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 266cef66bf96fc94c94abc46886e612611d2fae40170dd3bb91a3ba1d575749c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-beachmat
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-delayedarray
    - bioconductor-delayedmatrixstats
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-rhdf5
    - bioconductor-rhdf5lib
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - bioconductor-tximport
    - r-base
    - r-data.table
    - r-dplyr
    - r-ggbeeswarm
    - r-ggplot2
    - r-matrix
    - r-plyr
    - 'r-rcpp >=0.12.14'
    - r-reshape2
    - r-rjson
    - r-shiny
    - r-shinydashboard
    - r-viridis
  run:
    - bioconductor-beachmat
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-delayedarray
    - bioconductor-delayedmatrixstats
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-rhdf5
    - bioconductor-rhdf5lib
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - bioconductor-tximport
    - r-base
    - r-data.table
    - r-dplyr
    - r-ggbeeswarm
    - r-ggplot2
    - r-matrix
    - r-plyr
    - 'r-rcpp >=0.12.14'
    - r-reshape2
    - r-rjson
    - r-shiny
    - r-shinydashboard
    - r-viridis
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'A collection of tools for doing various analyses of single-cell RNA-seq gene expression data, with a focus on quality control.'

