{% set version = "1.52.0" %}
{% set name = "ScISI" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 52d824983f017feeb7703a091d81256abcc278015a648dfae83649af9c80d145
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-apcomplex
    - bioconductor-go.db
    - bioconductor-org.sc.sgd.db
    - bioconductor-rpsixml
    - r-base
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-apcomplex
    - bioconductor-go.db
    - bioconductor-org.sc.sgd.db
    - bioconductor-rpsixml
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'Package to create In Silico Interactomes'

