{% set version = "1.44.0" %}
{% set name = "oligo" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 4c7d85628fec0db359e58bd42b16f084cdcbe7ab07044310b9162e95ede4b073
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affxparser >=1.39.4'
    - 'bioconductor-affyio >=1.35.0'
    - 'bioconductor-biobase >=2.27.3'
    - 'bioconductor-biocgenerics >=0.13.11'
    - 'bioconductor-biostrings >=2.35.12'
    - 'bioconductor-oligoclasses >=1.29.6'
    - 'bioconductor-preprocesscore >=1.29.0'
    - bioconductor-zlibbioc
    - r-base
    - 'r-dbi >=0.3.1'
    - r-ff
    - 'r-rsqlite >=1.0.0'
  run:
    - 'bioconductor-affxparser >=1.39.4'
    - 'bioconductor-affyio >=1.35.0'
    - 'bioconductor-biobase >=2.27.3'
    - 'bioconductor-biocgenerics >=0.13.11'
    - 'bioconductor-biostrings >=2.35.12'
    - 'bioconductor-oligoclasses >=1.29.6'
    - 'bioconductor-preprocesscore >=1.29.0'
    - bioconductor-zlibbioc
    - r-base
    - 'r-dbi >=0.3.1'
    - r-ff
    - 'r-rsqlite >=1.0.0'
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'A package to analyze oligonucleotide arrays (expression/SNP/tiling/exon) at probe-level. It currently supports Affymetrix (CEL files) and NimbleGen arrays (XYS files).'

