{% set version = "2.16.0" %}
{% set name = "SomaticSignatures" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: dfb8755b115406e213873fae3241c9422a0c15ad17596a9c859177e8f24a8c95
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-ggbio
    - bioconductor-iranges
    - bioconductor-pcamethods
    - bioconductor-s4vectors
    - bioconductor-variantannotation
    - r-base
    - r-ggplot2
    - r-nmf
    - r-proxy
    - r-reshape2
  run:
    - bioconductor-biobase
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-ggbio
    - bioconductor-iranges
    - bioconductor-pcamethods
    - bioconductor-s4vectors
    - bioconductor-variantannotation
    - r-base
    - r-ggplot2
    - r-nmf
    - r-proxy
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'The SomaticSignatures package identifies mutational signatures of single nucleotide variants (SNVs).  It provides a infrastructure related to the methodology described in Nik-Zainal (2012, Cell), with flexibility in the matrix decomposition algorithms.'

