{% set version = "2.4.1" %}
{% set name = "synapter" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 34650a2b53e157ef1fb2a488fdbd73b80117369a07817c02771b77e8a0404479
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biostrings
    - 'bioconductor-cleaver >=1.3.3'
    - 'bioconductor-msnbase >=2.1.2'
    - bioconductor-multtest
    - bioconductor-qvalue
    - r-base
    - r-knitr
    - r-lattice
    - r-rcolorbrewer
    - 'r-readr >=0.2'
    - 'r-rmarkdown >=1.0'
  run:
    - bioconductor-biobase
    - bioconductor-biostrings
    - 'bioconductor-cleaver >=1.3.3'
    - 'bioconductor-msnbase >=2.1.2'
    - bioconductor-multtest
    - bioconductor-qvalue
    - r-base
    - r-knitr
    - r-lattice
    - r-rcolorbrewer
    - 'r-readr >=0.2'
    - 'r-rmarkdown >=1.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The synapter package provides functionality to reanalyse label-free proteomics data acquired on a Synapt G2 mass spectrometer. One or several runs, possibly processed with additional ion mobility separation to increase identification accuracy can be combined to other quantitation files to maximise identification and quantitation accuracy.'

