{% set version = "1.22.0" %}
{% set name = "MotifDb" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 79db31ce111250bb16bb78434632833cc369b6e0c65b7d37fc1f2b8e63b2ac60
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - r-base
    - r-splitstackshape
  run:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - r-base
    - r-splitstackshape
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic-2.0 | file LICENSE'
  summary: 'More than 9000 annotated position frequency matrices from 14 public sources, for multiple organisms.'

