{% set version = "1.4.1" %}
{% set name = "GenomicScores" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: db91e995ca16bc45bb36987eed0e2eb921c4190d272061fbbf454d5c61836575
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationhub
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.8'
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=2.3.23'
    - 'bioconductor-s4vectors >=0.7.21'
    - r-base
    - r-xml
  run:
    - bioconductor-annotationhub
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.8'
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=2.3.23'
    - 'bioconductor-s4vectors >=0.7.21'
    - r-base
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Provide infrastructure to store and access genomewide position-specific scores within R and Bioconductor.'

