{% set version = "1.6.0" %}
{% set name = "TVTB" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 4a30a085640cb5e77ef9bbf9f32f8e0033d94146cfd3912790749f1937fbcca2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationfilter
    - 'bioconductor-biocgenerics >=0.25.1'
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-ensembldb
    - bioconductor-ensemblvep
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-gviz
    - 'bioconductor-iranges >=2.7.1'
    - bioconductor-limma
    - bioconductor-rsamtools
    - 'bioconductor-s4vectors >=0.11.11'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.19.9'
    - r-base
    - r-ggally
    - r-ggplot2
    - r-reshape2
  run:
    - bioconductor-annotationfilter
    - 'bioconductor-biocgenerics >=0.25.1'
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-ensembldb
    - bioconductor-ensemblvep
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-gviz
    - 'bioconductor-iranges >=2.7.1'
    - bioconductor-limma
    - bioconductor-rsamtools
    - 'bioconductor-s4vectors >=0.11.11'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.19.9'
    - r-base
    - r-ggally
    - r-ggplot2
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'The package provides S4 classes and methods to filter, summarise and visualise genetic variation data stored in VCF files. In particular, the package extends the FilterRules class (S4Vectors package) to define news classes of filter rules applicable to the various slots of VCF objects. Functionalities are integrated and demonstrated in a Shiny web-application, the Shiny Variant Explorer (tSVE).'

