{% set version = "1.10.0" %}
{% set name = "GUIDEseq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 02b1c2a033ee3baf3caf97fc9db1457d7ae883e855a793781d8df2e6d9e4ec2d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-chippeakanno
    - bioconductor-crisprseek
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.7.3'
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=2.5.5'
    - bioconductor-limma
    - bioconductor-rsamtools
    - 'bioconductor-s4vectors >=0.9.6'
    - r-base
    - r-data.table
    - r-hash
    - r-matrixstats
  run:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-chippeakanno
    - bioconductor-crisprseek
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.7.3'
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=2.5.5'
    - bioconductor-limma
    - bioconductor-rsamtools
    - 'bioconductor-s4vectors >=0.9.6'
    - r-base
    - r-data.table
    - r-hash
    - r-matrixstats
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'The package implements GUIDE-seq analysis workflow including functions for obtaining unique insertion sites (proxy of cleavage sites), estimating the locations of the insertion sites, aka, peaks, merging estimated insertion sites from plus and minus strand, and performing off target search of the extended regions around insertion sites.'

