{% set version = "1.14.0" %}
{% set name = "missMethyl" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 3ac149ded3ef2eb2b1cbdec20706e11dfb2d45ef2eb3201dcd8f6570b0659afc
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-go.db
    - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
    - bioconductor-illuminahumanmethylation450kmanifest
    - bioconductor-illuminahumanmethylationepicanno.ilm10b2.hg19
    - bioconductor-illuminahumanmethylationepicmanifest
    - bioconductor-limma
    - bioconductor-methylumi
    - bioconductor-minfi
    - bioconductor-org.hs.eg.db
    - r-base
    - r-biasedurn
    - r-ruv
    - r-statmod
    - r-stringr
  run:
    - bioconductor-annotationdbi
    - bioconductor-go.db
    - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
    - bioconductor-illuminahumanmethylation450kmanifest
    - bioconductor-illuminahumanmethylationepicanno.ilm10b2.hg19
    - bioconductor-illuminahumanmethylationepicmanifest
    - bioconductor-limma
    - bioconductor-methylumi
    - bioconductor-minfi
    - bioconductor-org.hs.eg.db
    - r-base
    - r-biasedurn
    - r-ruv
    - r-statmod
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Normalisation and testing for differential variability and differential methylation for data from Illumina''s Infinium HumanMethylation450 array. The normalisation procedure is subset-quantile within-array normalisation (SWAN), which allows Infinium I and II type probes on a single array to be normalised together. The test for differential variability is based on an empirical Bayes version of Levene''s test. Differential methylation testing is performed using RUV, which can adjust for systematic errors of unknown origin in high-dimensional data by using negative control probes. Gene ontology analysis is performed by taking into account the number of probes per gene on the array.'

