{% set version = "1.24.0" %}
{% set name = "ReactomePA" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ef9896f14944f43514cc57cd3518e3e8060ed1f86274b84cef3939bfd8170a16
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - 'bioconductor-dose >=3.5.1'
    - bioconductor-enrichplot
    - bioconductor-graphite
    - bioconductor-reactome.db
    - r-base
    - r-ggplot2
    - r-ggraph
    - r-igraph
  run:
    - bioconductor-annotationdbi
    - 'bioconductor-dose >=3.5.1'
    - bioconductor-enrichplot
    - bioconductor-graphite
    - bioconductor-reactome.db
    - r-base
    - r-ggplot2
    - r-ggraph
    - r-igraph
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package provides functions for pathway analysis based on REACTOME pathway database. It implements enrichment analysis, gene set enrichment analysis and several functions for visualization.'

