{% set version = "1.32.0" %}
{% set name = "DEGraph" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: fd70e69c20e39e93ee0a53705191d9d9e94f1b6ac11ba373e15517c2fb9a6023
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-graph
    - bioconductor-kegggraph
    - bioconductor-ncigraph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
    - r-lattice
    - r-mvtnorm
    - r-r.methodss3
    - r-r.utils
    - r-rrcov
  run:
    - bioconductor-graph
    - bioconductor-kegggraph
    - bioconductor-ncigraph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
    - r-lattice
    - r-mvtnorm
    - r-r.methodss3
    - r-r.utils
    - r-rrcov
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'DEGraph implements recent hypothesis testing methods which directly assess whether a particular gene network is differentially expressed between two conditions. This is to be contrasted with the more classical two-step approaches which first test individual genes, then test gene sets for enrichment in differentially expressed genes. These recent methods take into account the topology of the network to yield more powerful detection procedures. DEGraph provides methods to easily test all KEGG pathways for differential expression on any gene expression data set and tools to visualize the results.'

