{% set version = "1.16.0" %}
{% set name = "QDNAseq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8d73b6224d1c82a2e8c540ec3c7c29ac6993704f9a4e024f03cdf1ee5d4d46de
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=2.18.0'
    - 'bioconductor-biocparallel >=1.6.6'
    - 'bioconductor-cghbase >=1.18.0'
    - 'bioconductor-cghcall >=2.18.0'
    - 'bioconductor-dnacopy >=1.32.0'
    - 'bioconductor-genomicranges >=1.20'
    - 'bioconductor-iranges >=2.2'
    - 'bioconductor-rsamtools >=1.20'
    - r-base
    - 'r-matrixstats >=0.50.2'
    - 'r-r.utils >=2.3.0'
  run:
    - 'bioconductor-biobase >=2.18.0'
    - 'bioconductor-biocparallel >=1.6.6'
    - 'bioconductor-cghbase >=1.18.0'
    - 'bioconductor-cghcall >=2.18.0'
    - 'bioconductor-dnacopy >=1.32.0'
    - 'bioconductor-genomicranges >=1.20'
    - 'bioconductor-iranges >=2.2'
    - 'bioconductor-rsamtools >=1.20'
    - r-base
    - 'r-matrixstats >=0.50.2'
    - 'r-r.utils >=2.3.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL
  summary: 'Quantitative DNA sequencing for chromosomal aberrations. The genome is divided into non-overlapping fixed-sized bins, number of sequence reads in each counted, adjusted with a simultaneous two-dimensional loess correction for sequence mappability and GC content, and filtered to remove spurious regions in the genome. Downstream steps of segmentation and calling are also implemented via packages DNAcopy and CGHcall, respectively.'

