{% set version = "1.10.0" %}
{% set name = "ProteomicsAnnotationHubData" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d9581b7a047cad2489ddc313dbeace66a42194ac454651271f3d03db3e96bda0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationhub >=2.1.45'
    - bioconductor-annotationhubdata
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-msnbase
    - 'bioconductor-mzr >=2.3.2'
    - r-base
    - r-rcurl
  run:
    - 'bioconductor-annotationhub >=2.1.45'
    - bioconductor-annotationhubdata
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-msnbase
    - 'bioconductor-mzr >=2.3.2'
    - r-base
    - r-rcurl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'These recipes convert a variety and a growing number of public proteomics data sets into easily-used standard Bioconductor data structures.'

