{% set version = "2.46.0" %}
{% set name = "GOstats" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 00b769e3bee17a76d9962461594a8b82da55610032658cc414bca4567ef3b5c4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotate >=1.13.2'
    - 'bioconductor-annotationdbi >=0.0.89'
    - bioconductor-annotationforge
    - 'bioconductor-biobase >=1.15.29'
    - 'bioconductor-category >=2.43.2'
    - 'bioconductor-go.db >=1.13.0'
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
  run:
    - 'bioconductor-annotate >=1.13.2'
    - 'bioconductor-annotationdbi >=0.0.89'
    - bioconductor-annotationforge
    - 'bioconductor-biobase >=1.15.29'
    - 'bioconductor-category >=2.43.2'
    - 'bioconductor-go.db >=1.13.0'
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'A set of tools for interacting with GO and microarray data. A variety of basic manipulation tools for graphs, hypothesis testing and other simple calculations.'

