{% set version = "1.16.0" %}
{% set name = "PECA" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: c5b2e956f358d0c71ba825d877f4fa8c9085bdb6dc6ab750230535c5996bc42f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-genefilter
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-rots
    - r-aroma.affymetrix
    - r-aroma.core
    - r-base
  run:
    - bioconductor-affy
    - bioconductor-genefilter
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-rots
    - r-aroma.affymetrix
    - r-aroma.core
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Calculates Probe-level Expression Change Averages (PECA) to identify differential expression in Affymetrix gene expression microarray studies or in proteomic studies using peptide-level mesurements respectively.'

