{% set version = "1.48.0" %}
{% set name = "BioMVCClass" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 0fc37d1bb8c04530f42a99d925e9dc4c23bbc877466947b4f1eecc8481f9d9c4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-graph
    - bioconductor-mvcclass
    - bioconductor-rgraphviz
    - r-base
  run:
    - bioconductor-biobase
    - bioconductor-graph
    - bioconductor-mvcclass
    - bioconductor-rgraphviz
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'Creates classes used in model-view-controller (MVC) design'

