{% set version = "1.58.0" %}
{% set name = "affy" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 26cef02431581909471bb637ba03c736fde6787699593c9c0ea2bea8cb41b86b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affyio >=1.13.3'
    - 'bioconductor-biobase >=2.5.5'
    - 'bioconductor-biocgenerics >=0.1.12'
    - bioconductor-biocinstaller
    - bioconductor-preprocesscore
    - bioconductor-zlibbioc
    - r-base
  run:
    - 'bioconductor-affyio >=1.13.3'
    - 'bioconductor-biobase >=2.5.5'
    - 'bioconductor-biocgenerics >=0.1.12'
    - bioconductor-biocinstaller
    - bioconductor-preprocesscore
    - bioconductor-zlibbioc
    - r-base
  build:
    - {{ compiler('c') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2.0)'
  summary: 'The package contains functions for exploratory oligonucleotide array analysis. The dependence on tkWidgets only concerns few convenience functions. ''affy'' is fully functional without it.'

