{% set version = "2.8.0" %}
{% set name = "DiffBind" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 50478712ff5b0fe9dd47a9879ddde81a611a1dcf117e84c7634c8cd3fef230f0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocparallel
    - bioconductor-deseq2
    - bioconductor-edger
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - 'bioconductor-rsamtools >=1.19.38'
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-systempiper
    - bioconductor-zlibbioc
    - r-amap
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-gplots
    - r-lattice
    - r-locfit
    - r-rcolorbrewer
    - r-rcpp
  run:
    - bioconductor-biocparallel
    - bioconductor-deseq2
    - bioconductor-edger
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - 'bioconductor-rsamtools >=1.19.38'
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-systempiper
    - bioconductor-zlibbioc
    - r-amap
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-gplots
    - r-lattice
    - r-locfit
    - r-rcolorbrewer
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Compute differentially bound sites from multiple ChIP-seq experiments using affinity (quantitative) data. Also enables occupancy (overlap) analysis and plotting functions.'

