{% set version = "1.14.0" %}
{% set name = "MBASED" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: c5770fa061f34e461613f9946d4d18d0a1d9b276ab60883060f31f8c199b1ed3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-genomicranges
    - bioconductor-summarizedexperiment
    - r-base
    - r-runit
  run:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-genomicranges
    - bioconductor-summarizedexperiment
    - r-base
    - r-runit
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'The package implements MBASED algorithm for detecting allele-specific gene expression from RNA count data, where allele counts at individual loci (SNVs) are integrated into a gene-specific measure of ASE, and utilizes simulations to appropriately assess the statistical significance of observed ASE.'

