{% set version = "1.14.0" %}
{% set name = "systemPipeR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 95963a20ac6c26c195b3c36c1ec8091f4f12dc3fd1de3adf067ed63a4cbba094
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-deseq2
    - bioconductor-edger
    - 'bioconductor-genomicfeatures >=1.31.3'
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-gostats
    - bioconductor-limma
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-shortread >=1.37.1'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.25.11'
    - r-base
    - r-batchjobs
    - r-ggplot2
    - r-pheatmap
    - r-rjson
  run:
    - bioconductor-annotate
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-deseq2
    - bioconductor-edger
    - 'bioconductor-genomicfeatures >=1.31.3'
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-gostats
    - bioconductor-limma
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-shortread >=1.37.1'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.25.11'
    - r-base
    - r-batchjobs
    - r-ggplot2
    - r-pheatmap
    - r-rjson
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'R package for building and running automated end-to-end analysis workflows for a wide range of next generation sequence (NGS) applications such as RNA-Seq, ChIP-Seq, VAR-Seq and Ribo-Seq. Important features include a uniform workflow interface across different NGS applications, automated report generation, and support for running both R and command-line software, such as NGS aligners or peak/variant callers, on local computers or compute clusters. Efficient handling of complex sample sets and experimental designs is facilitated by a consistently implemented sample annotation infrastructure. Instructions for using systemPipeR are given in the Overview Vignette (HTML). The remaining Vignettes, linked below, are workflow templates for common NGS use cases.'

