{% set version = "1.12.1" %}
{% set name = "RnBeads" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: fb610fa5b63641311d1ce27789a8bdc220f864e84f02a34d11dfc0b4e3f4d80a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-methylumi
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-cluster
    - r-ff
    - r-fields
    - 'r-ggplot2 >=0.9.2'
    - r-gplots
    - r-gridextra
    - r-mass
    - r-matrixstats
    - r-plyr
  run:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-methylumi
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-cluster
    - r-ff
    - r-fields
    - 'r-ggplot2 >=0.9.2'
    - r-gplots
    - r-gridextra
    - r-mass
    - r-matrixstats
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'RnBeads facilitates comprehensive analysis of various types of DNA methylation data at the genome scale.'

