{% set version = "1.20.0" %}
{% set name = "epigenomix" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: fa526d60cae35c4ff89fa4e1124e746c196d691176af8a5ccfba04554b883203
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-beadarray
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-mcmcpack
  run:
    - bioconductor-beadarray
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-mcmcpack
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL-3
  summary: 'A package for the integrative analysis of RNA-seq or microarray based gene transcription and histone modification data obtained by ChIP-seq. The package provides methods for data preprocessing and matching as well as methods for fitting bayesian mixture models in order to detect genes with differences in both data types.'

