{% set version = "1.4.0" %}
{% set name = "IMAS" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: cef75e8992be51b77d0053e960560d2865bcf9d44fd6f2a6415b1eaebbb7c752
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-ivas
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - r-base
    - r-doparallel
    - r-foreach
    - r-ggfortify
    - r-ggplot2
    - r-gridextra
    - r-lattice
    - r-lme4
    - r-matrix
    - r-survival
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-ivas
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - r-base
    - r-doparallel
    - r-foreach
    - r-ggfortify
    - r-ggplot2
    - r-gridextra
    - r-lattice
    - r-lme4
    - r-matrix
    - r-survival
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Integrative analysis of Multi-omics data for Alternative splicing.'

