{% set version = "1.30.0" %}
{% set name = "LVSmiRNA" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 605280d9b3dd048e41f7bf3d5c225b642b199b1b3ab35c361122ce239f5018f9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-limma
    - bioconductor-vsn
    - bioconductor-zlibbioc
    - r-base
    - r-mass
    - r-quantreg
    - r-sparsem
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-limma
    - bioconductor-vsn
    - bioconductor-zlibbioc
    - r-base
    - r-mass
    - r-quantreg
    - r-sparsem
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Normalization of Agilent miRNA arrays.'

