{% set version = "1.26.1" %}
{% set name = "graphite" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 571a92944b255a6236843f9ed1a1e5c29936216922975cb424f68a2361c9c94e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.42.1,<1.44.0'
    - 'bioconductor-graph >=1.58.0,<1.60.0'
    - r-base
    - r-checkmate
    - r-httr
    - r-rappdirs
  run:
    - 'bioconductor-annotationdbi >=1.42.1,<1.44.0'
    - 'bioconductor-graph >=1.58.0,<1.60.0'
    - r-base
    - r-checkmate
    - r-httr
    - r-rappdirs
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: AGPL-3
  summary: 'Graph objects from pathway topology derived from Biocarta, HumanCyc, KEGG, NCI, Panther, Reactome and SPIKE databases.'


