{% set version = "1.26.2" %}
{% set name = "minfi" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: e0567ac79a10eff553198943eed842a1000cefc18df03d30201a9bbdbf50d9ff
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=2.33.2'
    - 'bioconductor-biocgenerics >=0.15.3'
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - 'bioconductor-bumphunter >=1.1.9'
    - 'bioconductor-delayedarray >=0.5.23'
    - bioconductor-delayedmatrixstats
    - bioconductor-genefilter
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-geoquery
    - bioconductor-hdf5array
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-s4vectors
    - bioconductor-siggenes
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
    - r-beanplot
    - r-data.table
    - r-lattice
    - r-mass
    - r-mclust
    - r-nlme
    - r-nor1mix
    - r-quadprog
    - r-rcolorbrewer
    - r-reshape
  run:
    - 'bioconductor-biobase >=2.33.2'
    - 'bioconductor-biocgenerics >=0.15.3'
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - 'bioconductor-bumphunter >=1.1.9'
    - 'bioconductor-delayedarray >=0.5.23'
    - bioconductor-delayedmatrixstats
    - bioconductor-genefilter
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-geoquery
    - bioconductor-hdf5array
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-s4vectors
    - bioconductor-siggenes
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
    - r-beanplot
    - r-data.table
    - r-lattice
    - r-mass
    - r-mclust
    - r-nlme
    - r-nor1mix
    - r-quadprog
    - r-rcolorbrewer
    - r-reshape
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Tools to analyze & visualize Illumina Infinium methylation arrays.'

