{% set version = "2.30.0" %}
{% set name = "beadarray" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: b62f7771a1a0ae050f5bd983182d57b857428e40c6076d67e6848855a7cbefe5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-beaddatapackr
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - r-base
    - r-ggplot2
    - r-reshape2
  run:
    - bioconductor-annotationdbi
    - bioconductor-beaddatapackr
    - 'bioconductor-biobase >=2.17.8'
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-limma
    - r-base
    - r-ggplot2
    - r-reshape2
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The package is able to read bead-level data (raw TIFFs and text files) output by BeadScan as well as bead-summary data from BeadStudio.  Methods for quality assessment and low-level analysis are provided.'

