{% set version = "1.28.0" %}
{% set name = "pvac" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: afc020ec92f2d744d3d54c042c0592410ce46ea0f7f5028693a16a64a7176233
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affy >=1.20.0'
    - bioconductor-biobase
    - r-base
  run:
    - 'bioconductor-affy >=1.20.0'
    - bioconductor-biobase
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2.0)'
  summary: 'The package contains the function for filtering genes by the proportion of variation accounted for by the first principal component (PVAC).'

