{% set version = "1.6.1" %}
{% set name = "GRmetrics" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 778a0930864c40b88337d9188bf20e4c3bc20d519fc3d9e38ebf5369d79955f9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-drc
    - r-ggplot2
    - r-plotly
  run:
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-drc
    - r-ggplot2
    - r-plotly
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Functions for calculating and visualizing growth-rate inhibition (GR) metrics.'

