{% set version = "2.32.0" %}
{% set name = "topGO" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 81f758e507ac28ec341ecad1a8d67e50b6619e4b2e8254274dfc2dd4e2b4dd17
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.7.19'
    - 'bioconductor-biobase >=2.0.0'
    - 'bioconductor-biocgenerics >=0.13.6'
    - 'bioconductor-go.db >=2.3.0'
    - 'bioconductor-graph >=1.14.0'
    - r-base
    - r-dbi
    - r-lattice
    - r-matrixstats
    - 'r-sparsem >=0.73'
  run:
    - 'bioconductor-annotationdbi >=1.7.19'
    - 'bioconductor-biobase >=2.0.0'
    - 'bioconductor-biocgenerics >=0.13.6'
    - 'bioconductor-go.db >=2.3.0'
    - 'bioconductor-graph >=1.14.0'
    - r-base
    - r-dbi
    - r-lattice
    - r-matrixstats
    - 'r-sparsem >=0.73'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'topGO package provides tools for testing GO terms while accounting for the topology of the GO graph. Different test statistics and different methods for eliminating local similarities and dependencies between GO terms can be implemented and applied.'

