{% set version = "1.32.3" %}
{% set name = "Rsamtools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 18da1af49cb11008d9c6b55e67f4a1859afd711e486ab09f23ee8e0185c8f2c2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.25.1'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.1.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-xvector >=0.19.7'
    - bioconductor-zlibbioc
    - r-base
    - r-bitops
  run:
    - 'bioconductor-biocgenerics >=0.25.1'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.1.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-xvector >=0.19.7'
    - bioconductor-zlibbioc
    - r-base
    - r-bitops
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic-2.0 | file LICENSE'
  summary: 'This package provides an interface to the ''samtools'', ''bcftools'', and ''tabix'' utilities (see ''LICENCE'') for manipulating SAM (Sequence Alignment / Map), FASTA, binary variant call (BCF) and compressed indexed tab-delimited (tabix) files.'

