{% set version = "1.14.0" %}
{% set name = "methylPipe" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1e05797af340863c335d3537282025e0c7092cae9aaa85b6dc8b030cc673622c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-marray
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=0.2.0'
    - r-base
    - r-data.table
    - r-gplots
  run:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-marray
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=0.2.0'
    - r-base
    - r-data.table
    - r-gplots
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL(>=2)
  summary: 'Memory efficient analysis of base resolution DNA methylation data in both the CpG and non-CpG sequence context. Integration of DNA methylation data derived from any methodology providing base- or low-resolution data.'

