{% set version = "1.12.0" %}
{% set name = "psygenet2r" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: c5edc497c9016d1ea4e61467c2ca3537f3d2b2d4304f5cfe24ebe9370ec75b66
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-bgeedb
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - bioconductor-biomart
    - bioconductor-go.db
    - bioconductor-topgo
    - r-base
    - r-ggplot2
    - r-igraph
    - r-labeling
    - r-rcurl
    - r-reshape2
    - r-stringr
  run:
    - bioconductor-bgeedb
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - bioconductor-biomart
    - bioconductor-go.db
    - bioconductor-topgo
    - r-base
    - r-ggplot2
    - r-igraph
    - r-labeling
    - r-rcurl
    - r-reshape2
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Package to retrieve data from PsyGeNET database (www.psygenet.org) and to perform comorbidity studies with PsyGeNET''s and user''s data.'

