{% set version = "1.20.0" %}
{% set name = "QuasR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 837ba80f1ca3408aa6511e2c7bf0d24683f2ae5cc854b2ab66f318a55369969e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocinstaller
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - 'bioconductor-genomicfeatures >=1.17.13'
    - bioconductor-genomicfiles
    - 'bioconductor-genomicranges >=1.13.3'
    - bioconductor-iranges
    - bioconductor-rbowtie
    - 'bioconductor-rsamtools >=1.19.38'
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-shortread >=1.19.1'
    - bioconductor-zlibbioc
    - r-base
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocinstaller
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - 'bioconductor-genomicfeatures >=1.17.13'
    - bioconductor-genomicfiles
    - 'bioconductor-genomicranges >=1.13.3'
    - bioconductor-iranges
    - bioconductor-rbowtie
    - 'bioconductor-rsamtools >=1.19.38'
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-shortread >=1.19.1'
    - bioconductor-zlibbioc
    - r-base
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package provides a framework for the quantification and analysis of Short Reads. It covers a complete workflow starting from raw sequence reads, over creation of alignments and quality control plots, to the quantification of genomic regions of interest.'

