{% set version = "1.6.2" %}
{% set name = "methylKit" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 11e1712bc5b29699a9425c8ddbf169e07fe5ca199563a3f68ae2c915820d1aa6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-fastseg
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.18.1'
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-qvalue
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.13.13'
    - bioconductor-zlibbioc
    - r-base
    - 'r-data.table >=1.9.6'
    - r-emdbook
    - r-gtools
    - r-kernsmooth
    - r-mclust
    - r-r.utils
    - r-rcpp
  run:
    - bioconductor-fastseg
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.18.1'
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-qvalue
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.13.13'
    - bioconductor-zlibbioc
    - r-base
    - 'r-data.table >=1.9.6'
    - r-emdbook
    - r-gtools
    - r-kernsmooth
    - r-mclust
    - r-r.utils
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'methylKit is an R package for DNA methylation analysis and annotation from high-throughput bisulfite sequencing. The package is designed to deal with sequencing data from RRBS and its variants, but also target-capture methods and whole genome bisulfite sequencing. It also has functions to analyze base-pair resolution 5hmC data from experimental protocols such as oxBS-Seq and TAB-Seq. Perl is needed to read SAM files only.'

