{% set version = "1.24.0" %}
{% set name = "ffpe" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: efaabc3e9c8582c5827793c6c232679c4d62a96812fa996a0aeb8796e7b66fb5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-lumi
    - bioconductor-methylumi
    - r-base
    - r-sfsmisc
    - r-ttr
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-lumi
    - bioconductor-methylumi
    - r-base
    - r-sfsmisc
    - r-ttr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>2)'
  summary: 'Identify low-quality data using metrics developed for expression data derived from Formalin-Fixed, Paraffin-Embedded (FFPE) data.  Also a function for making Concordance at the Top plots (CAT-plots).'

