{% set version = "1.8.2" %}
{% set name = "ggcyto" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 481774bcc1f99f4dfb3feb4083829c1ce5acebd2fd5670e316f17b4625a0edd9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-flowcore >=1.41.5'
    - 'bioconductor-flowworkspace >=3.17.24'
    - 'bioconductor-ncdfflow >=2.17.1'
    - r-base
    - r-data.table
    - 'r-ggplot2 >=2.2.1.9000'
    - r-gridextra
    - r-plyr
    - r-rcolorbrewer
    - r-rlang
    - r-scales
  run:
    - 'bioconductor-flowcore >=1.41.5'
    - 'bioconductor-flowworkspace >=3.17.24'
    - 'bioconductor-ncdfflow >=2.17.1'
    - r-base
    - r-data.table
    - 'r-ggplot2 >=2.2.1.9000'
    - r-gridextra
    - r-plyr
    - r-rcolorbrewer
    - r-rlang
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'With the dedicated fortify method implemented for flowSet, ncdfFlowSet and GatingSet classes, both raw and gated flow cytometry data can be plotted directly with ggplot. ggcyto wrapper and some customed layers also make it easy to add gates and population statistics to the plot.'

