{% set version = "1.38.0" %}
{% set name = "crlmm" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ce2821228fc573b1bc4dc36d783e74a9500601e13feb89cce877616d152e083a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affyio >=1.23.2'
    - 'bioconductor-biobase >=2.15.4'
    - bioconductor-biocgenerics
    - bioconductor-illuminaio
    - bioconductor-limma
    - 'bioconductor-oligoclasses >=1.21.12'
    - 'bioconductor-preprocesscore >=1.17.7'
    - bioconductor-snpchip
    - r-base
    - r-beanplot
    - r-ellipse
    - r-ff
    - r-foreach
    - r-lattice
    - r-matrixstats
    - r-mvtnorm
    - 'r-rcppeigen >=0.3.1.2.1'
    - r-vgam
  run:
    - 'bioconductor-affyio >=1.23.2'
    - 'bioconductor-biobase >=2.15.4'
    - bioconductor-biocgenerics
    - bioconductor-illuminaio
    - bioconductor-limma
    - 'bioconductor-oligoclasses >=1.21.12'
    - 'bioconductor-preprocesscore >=1.17.7'
    - bioconductor-snpchip
    - r-base
    - r-beanplot
    - r-ellipse
    - r-ff
    - r-foreach
    - r-lattice
    - r-matrixstats
    - r-mvtnorm
    - 'r-rcppeigen >=0.3.1.2.1'
    - r-vgam
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Faster implementation of CRLMM specific to SNP 5.0 and 6.0 arrays, as well as a copy number tool specific to 5.0, 6.0, and Illumina platforms.'

