{% set version = "1.20.2" %}
{% set name = "pRoloc" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8772783ee6bd4df8f733ab1874c73f3c3bfd6fe82e7b5cd7d0033536732eff4e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biomart
    - 'bioconductor-mlinterfaces >=1.37.1'
    - 'bioconductor-msnbase >=1.19.20'
    - r-base
    - r-caret
    - r-class
    - r-dendextend
    - r-e1071
    - r-fnn
    - r-ggplot2
    - r-gtools
    - r-hexbin
    - r-kernlab
    - r-knitr
    - r-lattice
    - r-mass
    - 'r-mclust >=4.3'
    - r-mvtnorm
    - r-nnet
    - r-plyr
    - r-proxy
    - r-randomforest
    - r-rcolorbrewer
    - 'r-rcpp >=0.10.3'
    - r-rcpparmadillo
    - r-sampling
    - r-scales
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biomart
    - 'bioconductor-mlinterfaces >=1.37.1'
    - 'bioconductor-msnbase >=1.19.20'
    - r-base
    - r-caret
    - r-class
    - r-dendextend
    - r-e1071
    - r-fnn
    - r-ggplot2
    - r-gtools
    - r-hexbin
    - r-kernlab
    - r-knitr
    - r-lattice
    - r-mass
    - 'r-mclust >=4.3'
    - r-mvtnorm
    - r-nnet
    - r-plyr
    - r-proxy
    - r-randomforest
    - r-rcolorbrewer
    - 'r-rcpp >=0.10.3'
    - r-rcpparmadillo
    - r-sampling
    - r-scales
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The pRoloc package implements machine learning and visualisation methods for the analysis and interogation of quantitiative mass spectrometry data to reliably infer protein sub-cellular localisation.'

