{% set version = "1.16.2" %}
{% set name = "DOQTL" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a44668e9af9dfea9d82e85ba2e83d6034e526b6fc95ab60612f4ae8aeae08fe1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-annotationtools
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-bsgenome.mmusculus.ucsc.mm10
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rhdf5
    - bioconductor-rsamtools
    - bioconductor-variantannotation
    - r-base
    - r-corpcor
    - r-doparallel
    - r-foreach
    - r-fpc
    - r-hwriter
    - r-iterators
    - r-mclust
    - r-qtlrel
    - r-regress
    - r-runit
    - r-xml
  run:
    - bioconductor-annotate
    - bioconductor-annotationtools
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-bsgenome.mmusculus.ucsc.mm10
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rhdf5
    - bioconductor-rsamtools
    - bioconductor-variantannotation
    - r-base
    - r-corpcor
    - r-doparallel
    - r-foreach
    - r-fpc
    - r-hwriter
    - r-iterators
    - r-mclust
    - r-qtlrel
    - r-regress
    - r-runit
    - r-xml
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'DOQTL is a quantitative trait locus (QTL) mapping pipeline designed for Diversity Outbred mice and other multi-parent outbred populations. The package reads in data from genotyping arrays and perform haplotype reconstruction using a hidden Markov model (HMM). The haplotype probabilities from the HMM are then used to perform linkage mapping. When founder sequences are available, DOQTL can use the haplotype reconstructions to impute the founder sequences onto DO genomes and perform association mapping.'

