{% set version = "1.8.0" %}
{% set name = "epivizrData" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 82701cbf197744d711c5f62274c56ce1b2d23d966bbd6443c20a890bf3f16d7d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-ensembldb
    - 'bioconductor-epivizrserver >=1.1.1'
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-organismdbi
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=0.2.0'
    - r-base
  run:
    - bioconductor-biobase
    - bioconductor-ensembldb
    - 'bioconductor-epivizrserver >=1.1.1'
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-organismdbi
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=0.2.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Serve data from Bioconductor Objects through a WebSocket connection.'

