{% set version = "1.16.1" %}
{% set name = "ChIPseeker" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: fe358c80a1a5f2d4ccbadcca59a23074aa5f81b681384fc1106066defa3581d6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-enrichplot
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicfeatures >=1.31.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.17.25'
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
    - r-base
    - r-boot
    - r-dplyr
    - 'r-ggplot2 >=2.2.0'
    - r-gplots
    - r-gridbase
    - r-gtools
    - r-magrittr
    - r-plotrix
    - r-rcolorbrewer
    - r-upsetr
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-enrichplot
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicfeatures >=1.31.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.17.25'
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
    - r-base
    - r-boot
    - r-dplyr
    - 'r-ggplot2 >=2.2.0'
    - r-gplots
    - r-gridbase
    - r-gtools
    - r-magrittr
    - r-plotrix
    - r-rcolorbrewer
    - r-upsetr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package implements functions to retrieve the nearest genes around the peak, annotate genomic region of the peak, statstical methods for estimate the significance of overlap among ChIP peak data sets, and incorporate GEO database for user to compare the own dataset with those deposited in database. The comparison can be used to infer cooperative regulation and thus can be used to generate hypotheses. Several visualization functions are implemented to summarize the coverage of the peak experiment, average profile and heatmap of peaks binding to TSS regions, genomic annotation, distance to TSS, and overlap of peaks or genes.'

