{% set version = "1.6.1" %}
{% set name = "MutationalPatterns" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 49726301308e489ec9de4d42bc29d1858af57b5b858de690edb20a22431907fb
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.18.0'
    - 'bioconductor-biostrings >=2.40.0'
    - 'bioconductor-genomeinfodb >=1.12.0'
    - 'bioconductor-genomicranges >=1.24.0'
    - 'bioconductor-iranges >=2.6.0'
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=1.2.2'
    - 'bioconductor-variantannotation >=1.18.1'
    - r-base
    - 'r-cowplot >=0.9.2'
    - 'r-ggdendro >=0.1-20'
    - 'r-ggplot2 >=2.1.0'
    - 'r-nmf >=0.20.6'
    - 'r-plyr >=1.8.3'
    - 'r-pracma >=1.8.8'
    - 'r-reshape2 >=1.4.1'
  run:
    - 'bioconductor-biocgenerics >=0.18.0'
    - 'bioconductor-biostrings >=2.40.0'
    - 'bioconductor-genomeinfodb >=1.12.0'
    - 'bioconductor-genomicranges >=1.24.0'
    - 'bioconductor-iranges >=2.6.0'
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=1.2.2'
    - 'bioconductor-variantannotation >=1.18.1'
    - r-base
    - 'r-cowplot >=0.9.2'
    - 'r-ggdendro >=0.1-20'
    - 'r-ggplot2 >=2.1.0'
    - 'r-nmf >=0.20.6'
    - 'r-plyr >=1.8.3'
    - 'r-pracma >=1.8.8'
    - 'r-reshape2 >=1.4.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'An extensive toolset for the characterization and visualization of a wide range of mutational patterns in base substitution catalogs.'

