{% set version = "1.20.0" %}
{% set name = "MethylSeekR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a77c81e78e8bdfe9fef27d56af407467395fcfad4d8e42a64e891acf65cfeda5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-bsgenome >=1.26.1'
    - 'bioconductor-geneplotter >=1.34.0'
    - 'bioconductor-genomicranges >=1.10.5'
    - 'bioconductor-iranges >=1.16.3'
    - 'bioconductor-rtracklayer >=1.16.3'
    - r-base
    - 'r-mhsmm >=0.4.4'
  run:
    - 'bioconductor-bsgenome >=1.26.1'
    - 'bioconductor-geneplotter >=1.34.0'
    - 'bioconductor-genomicranges >=1.10.5'
    - 'bioconductor-iranges >=1.16.3'
    - 'bioconductor-rtracklayer >=1.16.3'
    - r-base
    - 'r-mhsmm >=0.4.4'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'This is a package for the discovery of regulatory regions from Bis-seq data'

