{% set version = "2.14.1" %}
{% set name = "EDASeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e8695f6701f4b9f1af7d5cb622d366151ad8678bcd298c3b0e1cb7565ae2e024
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-aroma.light
    - 'bioconductor-biobase >=2.15.1'
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-deseq
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=1.13.9'
    - 'bioconductor-rsamtools >=1.5.75'
    - 'bioconductor-shortread >=1.11.42'
    - r-base
  run:
    - bioconductor-annotationdbi
    - bioconductor-aroma.light
    - 'bioconductor-biobase >=2.15.1'
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-deseq
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=1.13.9'
    - 'bioconductor-rsamtools >=1.5.75'
    - 'bioconductor-shortread >=1.11.42'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Numerical and graphical summaries of RNA-Seq read data. Within-lane normalization procedures to adjust for GC-content effect (or other gene-level effects) on read counts: loess robust local regression, global-scaling, and full-quantile normalization (Risso et al., 2011). Between-lane normalization procedures to adjust for distributional differences between lanes (e.g., sequencing depth): global-scaling and full-quantile normalization (Bullard et al., 2010).'

