{% set version = "1.26.0" %}
{% set name = "exomeCopy" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1cff39c955f7c20aaa429cea83cfb8fd831ed4d36500157521e831f20c6a7aab
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.23.16'
    - 'bioconductor-iranges >=2.5.27'
    - bioconductor-rsamtools
    - r-base
  run:
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.23.16'
    - 'bioconductor-iranges >=2.5.27'
    - bioconductor-rsamtools
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Detection of copy number variants (CNV) from exome sequencing samples, including unpaired samples.  The package implements a hidden Markov model which uses positional covariates, such as background read depth and GC-content, to simultaneously normalize and segment the samples into regions of constant copy count.'

