{% set version = "1.10.0" %}
{% set name = "PureCN" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 6b56936ed7aad965505f7d97eeb743a5d360be3d7c4dd202cb09cd7277fc92ab
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-dnacopy
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.20.3'
    - 'bioconductor-iranges >=2.2.1'
    - bioconductor-rhdf5
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.14.1'
    - r-base
    - r-data.table
    - r-futile.logger
    - r-ggplot2
    - r-gridextra
    - r-matrix
    - r-rcolorbrewer
    - r-vgam
  run:
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-dnacopy
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.20.3'
    - 'bioconductor-iranges >=2.2.1'
    - bioconductor-rhdf5
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.14.1'
    - r-base
    - r-data.table
    - r-futile.logger
    - r-ggplot2
    - r-gridextra
    - r-matrix
    - r-rcolorbrewer
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package estimates tumor purity, copy number, and loss of heterozygosity (LOH), and classifies single nucleotide variants (SNVs) by somatic status and clonality. PureCN is designed for targeted short read sequencing data, integrates well with standard somatic variant detection and copy number pipelines, and has support for tumor samples without matching normal samples.'

