{% set version = "1.12.1" %}
{% set name = "QuartPAC" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 9b8b85da86c4c8778060744baf5dd7e342e85a62376d5ef8f7b7bda81881c210
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-graphpac
    - bioconductor-ipac
    - bioconductor-spacepac
    - r-base
    - r-data.table
  run:
    - bioconductor-graphpac
    - bioconductor-ipac
    - bioconductor-spacepac
    - r-base
    - r-data.table
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Identifies clustering of somatic mutations in proteins over the entire quaternary structure.'

