{% set version = "1.16.0" %}
{% set name = "GenomicFiles" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b8ebf3927dafb3d9144042a357981aeb9841efbc53acf912f532bff859c11a2e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.11.2'
    - 'bioconductor-biocparallel >=1.1.0'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.7.7'
    - 'bioconductor-genomicranges >=1.31.16'
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.17.29'
    - 'bioconductor-rtracklayer >=1.25.3'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.11.2'
    - 'bioconductor-biocparallel >=1.1.0'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.7.7'
    - 'bioconductor-genomicranges >=1.31.16'
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.17.29'
    - 'bioconductor-rtracklayer >=1.25.3'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package provides infrastructure for parallel computations distributed ''by file'' or ''by range''. User defined MAPPER and REDUCER functions provide added flexibility for data combination and manipulation.'

