{% set version = "1.28.3" %}
{% set name = "htSeqTools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e7ee1b65265dc44256ec0618a907ae095a19c9aa3723a15229aa3f22011530a1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.0'
    - bioconductor-bsgenome
    - 'bioconductor-genomeinfodb >=1.1.3'
    - 'bioconductor-genomicranges >=1.17.11'
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
    - r-mass
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.0'
    - bioconductor-bsgenome
    - 'bioconductor-genomeinfodb >=1.1.3'
    - 'bioconductor-genomicranges >=1.17.11'
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
    - r-mass
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'We provide efficient, easy-to-use tools for High-Throughput Sequencing (ChIP-seq, RNAseq etc.). These include MDS plots (analogues to PCA), detecting inefficient immuno-precipitation or over-amplification artifacts, tools to identify and test for genomic regions with large accumulation of reads, and visualization of coverage profiles.'

