{% set version = "1.52.2" %}
{% set name = "affycoretools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 463446ea737148d9273378fb9c0823daebe36a00e3489db7431e7714fd294691
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-edger
    - bioconductor-gcrma
    - bioconductor-gostats
    - bioconductor-limma
    - bioconductor-oligoclasses
    - bioconductor-reportingtools
    - bioconductor-s4vectors
    - r-base
    - r-dbi
    - r-ggplot2
    - r-gplots
    - r-hwriter
    - r-lattice
    - r-rsqlite
    - r-xtable
  run:
    - bioconductor-affy
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-edger
    - bioconductor-gcrma
    - bioconductor-gostats
    - bioconductor-limma
    - bioconductor-oligoclasses
    - bioconductor-reportingtools
    - bioconductor-s4vectors
    - r-base
    - r-dbi
    - r-ggplot2
    - r-gplots
    - r-hwriter
    - r-lattice
    - r-rsqlite
    - r-xtable
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Various wrapper functions that have been written to streamline the more common analyses that a core Biostatistician might see.'

