{% set version = "1.22.0" %}
{% set name = "ensemblVEP" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d67a4978522768661287771397cfb203252a7ed15a9ecd43f4e3e7eb52641c9d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.26.0,<0.28.0'
    - 'bioconductor-biostrings >=2.48.0,<2.50.0'
    - 'bioconductor-genomeinfodb >=1.16.0,<1.18.0'
    - 'bioconductor-genomicranges >=1.32.7,<1.34.0'
    - 'bioconductor-s4vectors >=0.18.3,<0.20.0'
    - 'bioconductor-summarizedexperiment >=1.10.1,<1.12.0'
    - 'bioconductor-variantannotation >=1.26.1,<1.28.0'
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.26.0,<0.28.0'
    - 'bioconductor-biostrings >=2.48.0,<2.50.0'
    - 'bioconductor-genomeinfodb >=1.16.0,<1.18.0'
    - 'bioconductor-genomicranges >=1.32.7,<1.34.0'
    - 'bioconductor-s4vectors >=0.18.3,<0.20.0'
    - 'bioconductor-summarizedexperiment >=1.10.1,<1.12.0'
    - 'bioconductor-variantannotation >=1.26.1,<1.28.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Query the Ensembl Variant Effect Predictor via the perl API.'


