{% set version = "3.6.1" %}
{% set name = "DOSE" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7b38aa2e548912f8ec2e471841e83346d240ff5dd1d6c2620d2fe209ca8cc9df
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocparallel
    - bioconductor-do.db
    - bioconductor-fgsea
    - 'bioconductor-gosemsim >=2.0.0'
    - bioconductor-qvalue
    - bioconductor-s4vectors
    - r-base
    - r-ggplot2
    - r-reshape2
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocparallel
    - bioconductor-do.db
    - bioconductor-fgsea
    - 'bioconductor-gosemsim >=2.0.0'
    - bioconductor-qvalue
    - bioconductor-s4vectors
    - r-base
    - r-ggplot2
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package implements five methods proposed by Resnik, Schlicker, Jiang, Lin and Wang respectively for measuring semantic similarities among DO terms and gene products. Enrichment analyses including hypergeometric model and gene set enrichment analysis are also implemented for discovering disease associations of high-throughput biological data.'

