{% set version = "1.14.1" %}
{% set name = "GenomicTuples" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 95f5e2e9be0502a57e524894089027f5061bbb2a408fc78288ddf71d7faab5f0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.21.2'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.13'
    - 'bioconductor-s4vectors >=0.17.25'
    - r-base
    - r-data.table
    - 'r-rcpp >=0.11.2'
  run:
    - 'bioconductor-biocgenerics >=0.21.2'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.13'
    - 'bioconductor-s4vectors >=0.17.25'
    - r-base
    - r-data.table
    - 'r-rcpp >=0.11.2'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'GenomicTuples defines general purpose containers for storing genomic tuples. It aims to provide functionality for tuples of genomic co-ordinates that are analogous to those available for genomic ranges in the GenomicRanges Bioconductor package.'

