{% set version = "1.6.0" %}
{% set name = "StarBioTrek" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: eb4b648ac31d9fbe67f6197360aa1f3b33d37d91be427c3fddd3994524993d0f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-keggrest
    - bioconductor-org.hs.eg.db
    - bioconductor-spidermir
    - r-base
    - r-e1071
    - r-igraph
    - r-rocr
  run:
    - bioconductor-annotationdbi
    - bioconductor-keggrest
    - bioconductor-org.hs.eg.db
    - bioconductor-spidermir
    - r-base
    - r-e1071
    - r-igraph
    - r-rocr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'This tool StarBioTrek presents some methodologies to measure pathway activity and cross-talk among pathways integrating also the information of network data.'

