{% set version = "1.10.0" %}
{% set name = "BBCAnalyzer" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 0a1dfb72e58e6371d8120df49c3d79a8e1fa94e8fe7531413be03828ec257e5e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-base
  run:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL-3
  summary: 'BBCAnalyzer is a package for visualizing the relative or absolute number of bases, deletions and insertions at defined positions in sequence alignment data available as bam files in comparison to the reference bases. Markers for the relative base frequencies, the mean quality of the detected bases, known mutations or polymorphisms and variants called in the data may additionally be included in the plots.'

