{% set version = "1.16.1" %}
{% set name = "bsseq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a5463893c12ab9cf479ecc3d32113d2e436b657c02def951dcc56d748c1ab064
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-delayedarray >=0.5.34'
    - 'bioconductor-delayedmatrixstats >=1.1.12'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.29.14'
    - bioconductor-hdf5array
    - 'bioconductor-iranges >=2.11.16'
    - bioconductor-limma
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=1.9.18'
    - r-base
    - r-data.table
    - r-gtools
    - r-locfit
    - r-permute
    - 'r-r.utils >=2.0.0'
    - r-scales
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-delayedarray >=0.5.34'
    - 'bioconductor-delayedmatrixstats >=1.1.12'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicranges >=1.29.14'
    - bioconductor-hdf5array
    - 'bioconductor-iranges >=2.11.16'
    - bioconductor-limma
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=1.9.18'
    - r-base
    - r-data.table
    - r-gtools
    - r-locfit
    - r-permute
    - 'r-r.utils >=2.0.0'
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'A collection of tools for analyzing and visualizing bisulfite sequencing data.'

