{% set version = "1.32.0" %}
{% set name = "DESeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d5d29792e1ecdd29dd63b04eac4c0937eba68504a5f3227c3702b8a827e27d7a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=2.21.7'
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - r-base
    - r-lattice
    - r-locfit
    - r-mass
    - r-rcolorbrewer
  run:
    - 'bioconductor-biobase >=2.21.7'
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - r-base
    - r-lattice
    - r-locfit
    - r-mass
    - r-rcolorbrewer
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'Estimate variance-mean dependence in count data from high-throughput sequencing assays and test for differential expression based on a model using the negative binomial distribution'

