{% set version = "1.14.0" %}
{% set name = "FourCSeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 662cc98cd7609dfbd5a27abb608a0b9e860d3a255bb70657ce1bce8f5167802c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biostrings
    - 'bioconductor-deseq2 >=1.9.11'
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-ggbio
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-summarizedexperiment
    - r-base
    - r-fda
    - r-ggplot2
    - r-gtools
    - r-lsd
    - r-matrix
    - r-reshape2
  run:
    - bioconductor-biobase
    - bioconductor-biostrings
    - 'bioconductor-deseq2 >=1.9.11'
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-ggbio
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-summarizedexperiment
    - r-base
    - r-fda
    - r-ggplot2
    - r-gtools
    - r-lsd
    - r-matrix
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'FourCSeq is an R package dedicated to the analysis of (multiplexed) 4C sequencing data. The package provides a pipeline to detect specific interactions between DNA elements and identify differential interactions between conditions. The statistical analysis in R starts with individual bam files for each sample as inputs. To obtain these files, the package contains a python script (extdata/python/demultiplex.py) to demultiplex libraries and trim off primer sequences. With a standard alignment software the required bam files can be then be generated.'

