{% set version = "1.14.0" %}
{% set name = "M3D" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 306c0dc66599465d9799e2c3dbdf5cd94af4dda040ffeb14df29ac0edd432942
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biseq
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-rcpp
  run:
    - bioconductor-biocgenerics
    - bioconductor-biseq
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic License 2.0'
  summary: 'This package identifies statistically significantly differentially methylated regions of CpGs. It uses kernel methods (the Maximum Mean Discrepancy) to measure differences in methylation profiles, and relates these to inter-replicate changes, whilst accounting for variation in coverage profiles.'

