{% set version = "1.8.0" %}
{% set name = "DRIMSeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 336b05fcd2047fb41185437373557d3719e18b76bbf9bf0aade043f5473576d8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-edger
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - r-base
    - r-ggplot2
    - r-mass
    - r-reshape2
  run:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-edger
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - r-base
    - r-ggplot2
    - r-mass
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'The package provides two frameworks. One for the differential transcript usage analysis between different conditions and one for the tuQTL analysis. Both are based on modeling the counts of genomic features (i.e., transcripts) with the Dirichlet-multinomial distribution. The package also makes available functions for visualization and exploration of the data and results.'

