{% set version = "1.14.1" %}
{% set name = "compEpiTools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 745c5f30b63520ac68a9d88aa78bbc7ca71ad0c0d5db6094f8de1cabbe1bce15
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-iranges
    - bioconductor-methylpipe
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-topgo
    - bioconductor-xvector
    - r-base
    - r-gplots
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-iranges
    - bioconductor-methylpipe
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-topgo
    - bioconductor-xvector
    - r-base
    - r-gplots
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL
  summary: 'Tools for computational epigenomics developed for the analysis, integration and simultaneous visualization of various (epi)genomics data types across multiple genomic regions in multiple samples.'

