{% set version = "1.36.0" %}
{% set name = "flagme" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: c60206b52cbe07a4442c39bf7a2ffe3d5f1cfec1cd1c24975460f2f8af429a7f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-camera
    - bioconductor-gcspikelite
    - bioconductor-xcms
    - r-base
    - r-gplots
    - r-mass
    - r-sparsem
  run:
    - bioconductor-camera
    - bioconductor-gcspikelite
    - bioconductor-xcms
    - r-base
    - r-gplots
    - r-mass
    - r-sparsem
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'Fragment-level analysis of gas chromatography - mass spectrometry metabolomics data'

