{% set version = "1.26.0" %}
{% set name = "r3Cseq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 4f098382523baaec799ca476a4a4b9b37d074e2287d54bddd8698cb722344b0b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - r-base
    - r-data.table
    - r-rcolorbrewer
    - r-sqldf
    - r-vgam
  run:
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - r-base
    - r-data.table
    - r-rcolorbrewer
    - r-sqldf
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package is an implementation of data analysis for the long-range interactions from 3C-seq assay.'

