{% set version = "1.6.0" %}
{% set name = "HelloRanges" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e4fca3d307adf5e91c8f7b34ee7f1c4830136bb86c90e078f2bf302314bf5372
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.41.3'
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.15.7'
    - 'bioconductor-genomicfeatures >=1.31.5'
    - 'bioconductor-genomicranges >=1.31.10'
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-rsamtools
    - 'bioconductor-rtracklayer >=1.33.8'
    - 'bioconductor-s4vectors >=0.17.39'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.19.3'
    - r-base
    - r-docopt
  run:
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.41.3'
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.15.7'
    - 'bioconductor-genomicfeatures >=1.31.5'
    - 'bioconductor-genomicranges >=1.31.10'
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-rsamtools
    - 'bioconductor-rtracklayer >=1.33.8'
    - 'bioconductor-s4vectors >=0.17.39'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.19.3'
    - r-base
    - r-docopt
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Translates bedtools command-line invocations to R code calling functions from the Bioconductor *Ranges infrastructure. This is intended to educate novice Bioconductor users and to compare the syntax and semantics of the two frameworks.'

