{% set version = "0.20.0" %}
{% set name = "Pbase" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8c458b8265aa425b8edf715eaab650e31eea4ce90c56b1b18490052d0d24b9b2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationfilter
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biomart
    - 'bioconductor-biostrings >=2.47.5'
    - 'bioconductor-cleaver >=1.3.6'
    - 'bioconductor-ensembldb >=1.99.13'
    - 'bioconductor-genomicranges >=1.31.7'
    - bioconductor-gviz
    - 'bioconductor-iranges >=2.13.11'
    - 'bioconductor-msnbase >=1.15.5'
    - bioconductor-mzid
    - 'bioconductor-mzr >=1.99.1'
    - bioconductor-pviz
    - 'bioconductor-rtracklayer >=1.39.6'
    - 'bioconductor-s4vectors >=0.17.24'
    - r-base
    - r-rcpp
  run:
    - bioconductor-annotationfilter
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biomart
    - 'bioconductor-biostrings >=2.47.5'
    - 'bioconductor-cleaver >=1.3.6'
    - 'bioconductor-ensembldb >=1.99.13'
    - 'bioconductor-genomicranges >=1.31.7'
    - bioconductor-gviz
    - 'bioconductor-iranges >=2.13.11'
    - 'bioconductor-msnbase >=1.15.5'
    - bioconductor-mzid
    - 'bioconductor-mzr >=1.99.1'
    - bioconductor-pviz
    - 'bioconductor-rtracklayer >=1.39.6'
    - 'bioconductor-s4vectors >=0.17.24'
    - r-base
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'A set of classes and functions to investigate and understand protein sequence data in the context of a proteomics experiment.'

