{% set version = "1.22.0" %}
{% set name = "spliceR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 9106991819b538b1dda7b1861cd41b1a169ff9bc59f94cfc4c913f4c440a1a91
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-cummerbund
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - r-base
    - r-plyr
    - r-rcolorbrewer
    - r-venndiagram
  run:
    - bioconductor-cummerbund
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - r-base
    - r-plyr
    - r-rcolorbrewer
    - r-venndiagram
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'An R package for classification of alternative splicing and prediction of coding potential from RNA-seq data.'

