{% set version = "1.40.6" %}
{% set name = "rtracklayer" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 9470a3d892d7decd97a5fbe53298e6dada3847a595f00be2e02d057d3dedbdf3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.25.1'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicalignments >=1.15.6'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.13'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-xvector >=0.19.7'
    - bioconductor-zlibbioc
    - r-base
    - 'r-rcurl >=1.4-2'
    - 'r-xml >=1.98-0'
  run:
    - 'bioconductor-biocgenerics >=0.25.1'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomicalignments >=1.15.6'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.13'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-xvector >=0.19.7'
    - bioconductor-zlibbioc
    - r-base
    - 'r-rcurl >=1.4-2'
    - 'r-xml >=1.98-0'
  build:
    - {{ compiler('c') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic-2.0 + file LICENSE'
  summary: 'Extensible framework for interacting with multiple genome browsers (currently UCSC built-in) and manipulating annotation tracks in various formats (currently GFF, BED, bedGraph, BED15, WIG, BigWig and 2bit built-in). The user may export/import tracks to/from the supported browsers, as well as query and modify the browser state, such as the current viewport.'

