{% set version = "2.6.2" %}
{% set name = "BgeeDB" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: cc65796afb8b77a2b3b88fb80a7b5e9973b00af90321bd790d754f212ed7262e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-graph
    - bioconductor-topgo
    - r-base
    - r-data.table
    - r-digest
    - r-dplyr
    - r-rcurl
    - r-tidyr
  run:
    - bioconductor-biobase
    - bioconductor-graph
    - bioconductor-topgo
    - r-base
    - r-data.table
    - r-digest
    - r-dplyr
    - r-rcurl
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'A package for the annotation and gene expression data download from Bgee database, and TopAnat analysis: GO-like enrichment of anatomical terms, mapped to genes by expression patterns.'

