{% set version = "1.22.0" %}
{% set name = "methyAnalysis" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 71a4c455b3588f58cf259bdc4227f8a86549be36017de5df36515b3a9d9dba87
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-genefilter
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-genoset
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-lumi
    - bioconductor-methylumi
    - bioconductor-org.hs.eg.db
    - bioconductor-rtracklayer
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-base
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-genefilter
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-genoset
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-lumi
    - bioconductor-methylumi
    - bioconductor-org.hs.eg.db
    - bioconductor-rtracklayer
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'The methyAnalysis package aims for the DNA methylation data analysis and visualization. A MethyGenoSet class is defined to keep the chromosome location information together with the data. The package also includes functions of estimating the methylation levels from Methy-Seq data.'

