{% set version = "1.28.0" %}
{% set name = "GOFunction" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 578464fffe8f97854ac3d3f6a61a4d77ed2591c75e791ab6a9eaf546634e3b2f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.10.2'
    - 'bioconductor-biobase >=2.8.0'
    - 'bioconductor-go.db >=2.4.1'
    - 'bioconductor-graph >=1.26.0'
    - 'bioconductor-rgraphviz >=1.26.0'
    - r-base
    - r-dbi
    - 'r-sparsem >=0.85'
  run:
    - 'bioconductor-annotationdbi >=1.10.2'
    - 'bioconductor-biobase >=2.8.0'
    - 'bioconductor-go.db >=2.4.1'
    - 'bioconductor-graph >=1.26.0'
    - 'bioconductor-rgraphviz >=1.26.0'
    - r-base
    - r-dbi
    - 'r-sparsem >=0.85'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'The GO-function package provides a tool to address the redundancy that result from the GO structure or multiple annotation genes and derive biologically relevant functions from the statistically significant functions based on some intuitive assumption and statistical testing.'

