{% set version = "1.28.0" %}
{% set name = "NCIgraph" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7ac8d694bb1f475c72417160e51f3f059aca04f5c99dd97b84564580d0339bcf
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-graph
    - bioconductor-kegggraph
    - bioconductor-rbgl
    - bioconductor-rcy3
    - r-base
    - r-r.methodss3
  run:
    - bioconductor-graph
    - bioconductor-kegggraph
    - bioconductor-rbgl
    - bioconductor-rcy3
    - r-base
    - r-r.methodss3
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Provides various methods to load the pathways from the NCI Pathways Database in R graph objects and to re-format them.'

