{% set version = "1.16.0" %}
{% set name = "VariantFiltering" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 96013d7fde2454ac565a36fd01ef9593c338b0f6d25ed2ac491810350c801395
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.25.1'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.33.11'
    - bioconductor-bsgenome
    - 'bioconductor-genomeinfodb >=1.3.6'
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.19.13'
    - 'bioconductor-genomicscores >=1.0.0'
    - bioconductor-graph
    - bioconductor-gviz
    - 'bioconductor-iranges >=2.3.23'
    - bioconductor-rbgl
    - 'bioconductor-rsamtools >=1.17.8'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.13.29'
    - bioconductor-xvector
    - r-base
    - r-dt
    - r-shiny
    - r-shinyjs
    - r-shinythemes
    - r-shinytree
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.25.1'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.33.11'
    - bioconductor-bsgenome
    - 'bioconductor-genomeinfodb >=1.3.6'
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.19.13'
    - 'bioconductor-genomicscores >=1.0.0'
    - bioconductor-graph
    - bioconductor-gviz
    - 'bioconductor-iranges >=2.3.23'
    - bioconductor-rbgl
    - 'bioconductor-rsamtools >=1.17.8'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.13.29'
    - bioconductor-xvector
    - r-base
    - r-dt
    - r-shiny
    - r-shinyjs
    - r-shinythemes
    - r-shinytree
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Filter genetic variants using different criteria such as inheritance model, amino acid change consequence, minor allele frequencies across human populations, splice site strength, conservation, etc.'

