{% set version = "1.22.0" %}
{% set name = "PADOG" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: abbd2c0350d9c80a35ee33c88296bc9cd1bc2a8f67301714cd88a6b91bb9560f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-hgu133a.db
    - bioconductor-hgu133plus2.db
    - bioconductor-kegg.db
    - bioconductor-keggdzpathwaysgeo
    - bioconductor-limma
    - r-base
    - r-dorng
    - r-foreach
    - r-gsa
    - r-nlme
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-hgu133a.db
    - bioconductor-hgu133plus2.db
    - bioconductor-kegg.db
    - bioconductor-keggdzpathwaysgeo
    - bioconductor-limma
    - r-base
    - r-dorng
    - r-foreach
    - r-gsa
    - r-nlme
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'This package implements a general purpose gene set analysis method called PADOG that downplays the importance of genes that apear often accross the sets of genes to be analyzed. The package provides also a benchmark for gene set analysis methods in terms of sensitivity and ranking using 24 public datasets from KEGGdzPathwaysGEO package.'

