{% set version = "1.18.0" %}
{% set name = "TFBSTools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d15e80f4ab53ffe240b52a64cf00b82895bb6f9e8d414741fc07364c9ebb6bb8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=2.28'
    - 'bioconductor-biocgenerics >=0.14.0'
    - 'bioconductor-biocparallel >=1.2.21'
    - 'bioconductor-biostrings >=2.36.4'
    - 'bioconductor-bsgenome >=1.36.3'
    - 'bioconductor-cner >=1.4.0'
    - 'bioconductor-dirichletmultinomial >=1.10.0'
    - 'bioconductor-genomeinfodb >=1.6.1'
    - 'bioconductor-genomicranges >=1.20.6'
    - 'bioconductor-iranges >=2.2.7'
    - 'bioconductor-rtracklayer >=1.28.10'
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-seqlogo >=1.34.0'
    - 'bioconductor-xvector >=0.8.0'
    - r-base
    - 'r-catools >=1.17.1'
    - 'r-dbi >=0.6'
    - 'r-gtools >=3.5.0'
    - 'r-rsqlite >=1.0.0'
    - 'r-tfmpvalue >=0.0.5'
    - 'r-xml >=3.98-1.3'
  run:
    - 'bioconductor-biobase >=2.28'
    - 'bioconductor-biocgenerics >=0.14.0'
    - 'bioconductor-biocparallel >=1.2.21'
    - 'bioconductor-biostrings >=2.36.4'
    - 'bioconductor-bsgenome >=1.36.3'
    - 'bioconductor-cner >=1.4.0'
    - 'bioconductor-dirichletmultinomial >=1.10.0'
    - 'bioconductor-genomeinfodb >=1.6.1'
    - 'bioconductor-genomicranges >=1.20.6'
    - 'bioconductor-iranges >=2.2.7'
    - 'bioconductor-rtracklayer >=1.28.10'
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-seqlogo >=1.34.0'
    - 'bioconductor-xvector >=0.8.0'
    - r-base
    - 'r-catools >=1.17.1'
    - 'r-dbi >=0.6'
    - 'r-gtools >=3.5.0'
    - 'r-rsqlite >=1.0.0'
    - 'r-tfmpvalue >=0.0.5'
    - 'r-xml >=3.98-1.3'
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'TFBSTools is a package for the analysis and manipulation of transcription factor binding sites. It includes matrices conversion between Position Frequency Matirx (PFM), Position Weight Matirx (PWM) and Information Content Matrix (ICM). It can also scan putative TFBS from sequence/alignment, query JASPAR database and provides a wrapper of de novo motif discovery software.'

