{% set version = "1.50.0" %}
{% set name = "adSplit" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 5886e5d91dfa9c5bd859a0c6d158036a74dc8413f4874bc9fa7bbca46852257e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=1.5.12'
    - 'bioconductor-go.db >=1.8.1'
    - 'bioconductor-kegg.db >=1.8.1'
    - 'bioconductor-multtest >=1.6.0'
    - r-base
    - 'r-cluster >=1.9.1'
  run:
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=1.5.12'
    - 'bioconductor-go.db >=1.8.1'
    - 'bioconductor-kegg.db >=1.8.1'
    - 'bioconductor-multtest >=1.6.0'
    - r-base
    - 'r-cluster >=1.9.1'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'This package implements clustering of microarray gene expression profiles according to functional annotations. For each term genes are annotated to, splits into two subclasses are computed and a significance of the supporting gene set is determined.'

