{% set version = "1.6.1" %}
{% set name = "MADSEQ" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 00b90dd7263a14723a0405319c7a2598b27938f9271d722f51afb468f1857ec6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-preprocesscore
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - bioconductor-zlibbioc
    - r-base
    - r-coda
    - 'r-rjags >=4-6'
    - r-vcfr
    - r-vgam
  run:
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-preprocesscore
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - bioconductor-zlibbioc
    - r-base
    - r-coda
    - 'r-rjags >=4-6'
    - r-vcfr
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL(>=2)
  summary: 'The MADSEQ package provides a group of hierarchical Bayeisan models for the detection of mosaic aneuploidy, the inference of the type of aneuploidy and also for the quantification of the fraction of aneuploid cells in the sample.'

