{% set version = "1.10.2" %}
{% set name = "curatedMetagenomicData" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 873352867c5af358425f497c95e5a51834a73b808d28ab4319d9e5b1a5fa036a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationhub >=2.9.0'
    - 'bioconductor-biobase >=2.37.0'
    - 'bioconductor-experimenthub >=1.3.0'
    - bioconductor-s4vectors
    - r-base
    - 'r-dplyr >=0.5.0'
    - r-magrittr
    - r-tidyr
  run:
    - 'bioconductor-annotationhub >=2.9.0'
    - 'bioconductor-biobase >=2.37.0'
    - 'bioconductor-experimenthub >=1.3.0'
    - bioconductor-s4vectors
    - r-base
    - 'r-dplyr >=0.5.0'
    - r-magrittr
    - r-tidyr
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: ' The curatedMetagenomicData package provides microbial taxonomic, functional, and gene marker abundance for samples collected from different bodysites.'

