{% set version = "1.4.0" %}
{% set name = "NADfinder" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 01928a0c1fb3bf283a7a9fdd1a31ddaa3276cfdd5d155856fa701288425a6c2a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-atacseqqc
    - bioconductor-biocgenerics
    - bioconductor-csaw
    - bioconductor-empiricalbrownsmethod
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-trackviewer
    - r-base
    - r-baseline
    - r-corrplot
    - r-metap
    - r-signal
  run:
    - bioconductor-atacseqqc
    - bioconductor-biocgenerics
    - bioconductor-csaw
    - bioconductor-empiricalbrownsmethod
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-trackviewer
    - r-base
    - r-baseline
    - r-corrplot
    - r-metap
    - r-signal
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Nucleolus is an important structure inside the nucleus in eukaryotic cells. It is the site for transcribing rDNA into rRNA and for assembling ribosomes, aka ribosome biogenesis. In addition, nucleoli are dynamic hubs through which numerous proteins shuttle and contact specific non-rDNA genomic loci. Deep sequencing analyses of DNA associated with isolated nucleoli (NAD- seq) have shown that specific loci, termed nucleolus- associated domains (NADs) form frequent three- dimensional associations with nucleoli. NAD-seq has been used to study the biological functions of NAD and the dynamics of NAD distribution during embryonic stem cell (ESC) differentiation. Here, we developed a Bioconductor package NADfinder for bioinformatic analysis of the NAD-seq data, including normalization, smoothing, peak calling, peak trimming and annotation.'

