{% set version = "2.22.0" %}
{% set name = "cummeRbund" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: edc8d4c2e0b1cf6b8096ba69d84aecb083dea9a135a72d5b511d37ebb2e61596
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-gviz
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-fastcluster
    - r-ggplot2
    - r-plyr
    - r-reshape2
    - r-rsqlite
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.3.2'
    - bioconductor-gviz
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
    - r-fastcluster
    - r-ggplot2
    - r-plyr
    - r-reshape2
    - r-rsqlite
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Allows for persistent storage, access, exploration, and manipulation of Cufflinks high-throughput sequencing data.  In addition, provides numerous plotting functions for commonly used visualizations.'

