{% set version = "2.38.0" %}
{% set name = "KCsmart" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: f59ff9b95fad22a288befde7d70432ac5f1c6ec6fb48393486a23c8437dcf6eb
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-multtest
    - bioconductor-siggenes
    - r-base
    - r-kernsmooth
  run:
    - bioconductor-biocgenerics
    - bioconductor-multtest
    - bioconductor-siggenes
    - r-base
    - r-kernsmooth
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Multi sample aCGH analysis package using kernel convolution'

