{% set version = "1.20.0" %}
{% set name = "BiSeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b2c2794e56066315ef680cdc513797def0e92651cc1c722af9f6a8b884ca8de0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-globaltest
    - 'bioconductor-iranges >=1.17.24'
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=0.2.0'
    - r-base
    - r-betareg
    - r-formula
    - r-lokern
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-globaltest
    - 'bioconductor-iranges >=1.17.24'
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - 'bioconductor-summarizedexperiment >=0.2.0'
    - r-base
    - r-betareg
    - r-formula
    - r-lokern
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL-3
  summary: 'The BiSeq package provides useful classes and functions to handle and analyze targeted bisulfite sequencing (BS) data such as reduced-representation bisulfite sequencing (RRBS) data. In particular, it implements an algorithm to detect differentially methylated regions (DMRs). The package takes already aligned BS data from one or multiple samples.'

