{% set version = "1.18.5" %}
{% set name = "tRanslatome" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ba3713d72b18f107b2849c536790d80093e47aa769e2e899b313054f4a3c1749
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-anota
    - bioconductor-biobase
    - bioconductor-deseq
    - bioconductor-edger
    - bioconductor-gosemsim
    - bioconductor-heatplus
    - bioconductor-limma
    - bioconductor-org.hs.eg.db
    - bioconductor-rankprod
    - bioconductor-sigpathway
    - bioconductor-topgo
    - r-base
    - r-gplots
    - r-plotrix
  run:
    - bioconductor-anota
    - bioconductor-biobase
    - bioconductor-deseq
    - bioconductor-edger
    - bioconductor-gosemsim
    - bioconductor-heatplus
    - bioconductor-limma
    - bioconductor-org.hs.eg.db
    - bioconductor-rankprod
    - bioconductor-sigpathway
    - bioconductor-topgo
    - r-base
    - r-gplots
    - r-plotrix
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Detection of differentially expressed genes (DEGs) from the comparison of two biological conditions (treated vs. untreated, diseased vs. normal, mutant vs. wild-type) among different levels of gene expression (transcriptome ,translatome, proteome), using several statistical methods:  Rank Product, Translational Efficiency, t-test, Limma, ANOTA, DESeq, edgeR. Possibility to plot the results with scatterplots, histograms, MA plots, standard deviation (SD) plots, coefficient of variation (CV) plots. Detection of significantly enriched post-transcriptional regulatory factors (RBPs, miRNAs, etc) and Gene Ontology terms in the lists of DEGs previously identified for the two expression levels. Comparison of GO terms enriched only in one of the levels or in both. Calculation of the semantic similarity score between the lists of enriched GO terms coming from the two expression levels. Visual examination and comparison of the enriched terms with heatmaps, radar plots and barplots.'

