{% set version = "1.22.3" %}
{% set name = "CAGEr" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: c4651de70deada80715d6013a52f3818aa7fee025d558584edc416d1606a8d57
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-bsgenome
    - bioconductor-delayedarray
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - 'bioconductor-genomicranges >=1.23.16'
    - 'bioconductor-iranges >=2.5.27'
    - bioconductor-multiassayexperiment
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-beanplot
    - r-data.table
    - 'r-ggplot2 >=2.2.0'
    - r-gtools
    - r-kernsmooth
    - r-memoise
    - r-plyr
    - r-reshape
    - r-som
    - r-stringdist
    - r-stringi
    - r-vegan
    - r-vgam
  run:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-bsgenome
    - bioconductor-delayedarray
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - 'bioconductor-genomicranges >=1.23.16'
    - 'bioconductor-iranges >=2.5.27'
    - bioconductor-multiassayexperiment
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-beanplot
    - r-data.table
    - 'r-ggplot2 >=2.2.0'
    - r-gtools
    - r-kernsmooth
    - r-memoise
    - r-plyr
    - r-reshape
    - r-som
    - r-stringdist
    - r-stringi
    - r-vegan
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Preprocessing of CAGE sequencing data, identification and normalization of transcription start sites and downstream analysis of transcription start sites clusters (promoters).'

