{% set version = "1.18.0" %}
{% set name = "plethy" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: e840e9572a14cc8cba3c8d6a4167175a64715c6d09456c893d51fe01c4085add
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-streamer
    - r-base
    - 'r-dbi >=0.5-1'
    - r-ggplot2
    - r-plyr
    - r-rcolorbrewer
    - r-reshape2
    - 'r-rsqlite >=1.1'
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-streamer
    - r-base
    - 'r-dbi >=0.5-1'
    - r-ggplot2
    - r-plyr
    - r-rcolorbrewer
    - r-reshape2
    - 'r-rsqlite >=1.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package provides the infrastructure and tools to import, query and perform basic analysis of whole body plethysmography and metabolism data.  Currently support is limited to data derived from Buxco respirometry instruments as exported by their FinePointe software.'

