{% set version = "1.10.1" %}
{% set name = "variancePartition" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 72d8386a63273693c27139a56e1a90a52b45ab4912cebb3456758166c84cf289
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-limma
    - r-base
    - r-colorramps
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-gplots
    - r-iterators
    - 'r-lme4 >=1.1-10'
    - r-lmertest
    - r-mass
    - 'r-pbkrtest >=0.4-4'
    - r-reshape2
    - r-scales
  run:
    - bioconductor-biobase
    - bioconductor-limma
    - r-base
    - r-colorramps
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-gplots
    - r-iterators
    - 'r-lme4 >=1.1-10'
    - r-lmertest
    - r-mass
    - 'r-pbkrtest >=0.4-4'
    - r-reshape2
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Quantify and interpret multiple sources of biological and technical variation in gene expression experiments. Uses a linear mixed model to quantify variation in gene expression attributable to individual, tissue, time point, or technical variables.  Includes dream differential expression analysis for repeated measures.'

