{% set version = "1.24.2" %}
{% set name = "iPAC" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: f5a446e34d6139f6f05be29a9cb8a448fc2ad65e642a923a998a409d92cee21c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-multtest
    - r-base
    - r-gdata
    - r-scatterplot3d
  run:
    - bioconductor-biostrings
    - bioconductor-multtest
    - r-base
    - r-gdata
    - r-scatterplot3d
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'iPAC is a novel tool to identify somatic amino acid mutation clustering within proteins while taking into account protein structure.'

