{% set version = "1.14.0" %}
{% set name = "SGSeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e61fb11182dcbaf177f882b46ff4df73e58d77e2cfdf94aee5f8ed473179c387
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.47.6'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.15.7'
    - 'bioconductor-genomicfeatures >=1.31.5'
    - 'bioconductor-genomicranges >=1.31.10'
    - 'bioconductor-iranges >=2.13.15'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.28'
    - bioconductor-summarizedexperiment
    - r-base
    - r-igraph
    - r-runit
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.47.6'
    - bioconductor-genomeinfodb
    - 'bioconductor-genomicalignments >=1.15.7'
    - 'bioconductor-genomicfeatures >=1.31.5'
    - 'bioconductor-genomicranges >=1.31.10'
    - 'bioconductor-iranges >=2.13.15'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.28'
    - bioconductor-summarizedexperiment
    - r-base
    - r-igraph
    - r-runit
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'SGSeq is a software package for analyzing splice events from RNA-seq data. Input data are RNA-seq reads mapped to a reference genome in BAM format. Genes are represented as a splice graph, which can be obtained from existing annotation or predicted from the mapped sequence reads. Splice events are identified from the graph and are quantified locally using structurally compatible reads at the start or end of each splice variant. The software includes functions for splice event prediction, quantification, visualization and interpretation.'

