{% set version = "1.16.0" %}
{% set name = "GenomicAlignments" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 5c31ea7deaf17c3ea3a66fe41dfce754b5495f65a28be7860042ae392d13f102
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.15.3'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.13.1'
    - 'bioconductor-genomicranges >=1.31.19'
    - 'bioconductor-iranges >=2.13.25'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.28'
    - 'bioconductor-summarizedexperiment >=1.9.13'
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.15.3'
    - bioconductor-biocparallel
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomeinfodb >=1.13.1'
    - 'bioconductor-genomicranges >=1.31.19'
    - 'bioconductor-iranges >=2.13.25'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.28'
    - 'bioconductor-summarizedexperiment >=1.9.13'
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Provides efficient containers for storing and manipulating short genomic alignments (typically obtained by aligning short reads to a reference genome). This includes read counting, computing the coverage, junction detection, and working with the nucleotide content of the alignments.'

