{% set version = "1.6.2" %}
{% set name = "KEGGlincs" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: fa61e9faa467beb8500f68dcce170d8a093bf073798d13e9a58f9d6eea6b0d45
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-hgu133a.db
    - bioconductor-kegggraph
    - bioconductor-keggrest
    - bioconductor-kodata
    - 'bioconductor-org.hs.eg.db >=3.3.0'
    - r-base
    - r-gtools
    - r-httr
    - r-igraph
    - r-plyr
    - r-rjsonio
    - r-xml
  run:
    - bioconductor-annotationdbi
    - bioconductor-hgu133a.db
    - bioconductor-kegggraph
    - bioconductor-keggrest
    - bioconductor-kodata
    - 'bioconductor-org.hs.eg.db >=3.3.0'
    - r-base
    - r-gtools
    - r-httr
    - r-igraph
    - r-plyr
    - r-rjsonio
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'See what is going on ''under the hood'' of KEGG pathways by explicitly re-creating the pathway maps from information obtained from KGML files.'

