{% set version = "1.6.0" %}
{% set name = "yamss" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 0ed9549260a45ad3063d4ff19186c744de7c3279c8666aa1fa692ea9cfceff61
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.15.3'
    - bioconductor-ebimage
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-mzr
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-data.table
    - r-matrix
  run:
    - 'bioconductor-biocgenerics >=0.15.3'
    - bioconductor-ebimage
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-mzr
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-data.table
    - r-matrix
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Tools to analyze and visualize high-throughput metabolomics data aquired using chromatography-mass spectrometry. These tools preprocess data in a way that enables reliable and powerful differential analysis.'

