{% set version = "1.14.0" %}
{% set name = "Rnits" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 25baebc9454e10cdefafa34ae48dbd9a14bfde6ebf7d280bbdd1ed6d2ea0b1ab
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-qvalue
    - r-base
    - r-boot
    - r-ggplot2
    - r-reshape2
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-qvalue
    - r-base
    - r-boot
    - r-ggplot2
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'R/Bioconductor package for normalization, curve registration and inference in time course gene expression data'

