{% set version = "2.14.0" %}
{% set name = "mzR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 2fabfa09eb86627bab92e57ed4ba52b4c02279fafb382295a4b0e355f01215a4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.6'
    - 'bioconductor-protgenerics >=1.9.1'
    - 'bioconductor-rhdf5lib >=1.1.4'
    - bioconductor-zlibbioc
    - r-base
    - 'r-rcpp >=0.10.1'
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.13.6'
    - 'bioconductor-protgenerics >=1.9.1'
    - 'bioconductor-rhdf5lib >=1.1.4'
    - bioconductor-zlibbioc
    - r-base
    - 'r-rcpp >=0.10.1'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'mzR provides a unified API to the common file formats and parsers available for mass spectrometry data. It comes with a wrapper for the ISB random access parser for mass spectrometry mzXML, mzData and mzML files. The package contains the original code written by the ISB, and a subset of the proteowizard library for mzML and mzIdentML. The netCDF reading code has previously been used in XCMS.'

