{% set version = "2.14.0" %}
{% set name = "wavClusteR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: f5076a5fa67e32d22faa10e696558dc5b9bd251bac83070ba8ef8ebca8ab8526
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomicfeatures >=1.31.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-rsamtools
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.25'
    - r-base
    - r-foreach
    - r-ggplot2
    - r-hmisc
    - r-mclust
    - r-seqinr
    - r-stringr
    - r-wmtsa
  run:
    - bioconductor-biocgenerics
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-genomicfeatures >=1.31.3'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-rsamtools
    - 'bioconductor-rtracklayer >=1.39.7'
    - 'bioconductor-s4vectors >=0.17.25'
    - r-base
    - r-foreach
    - r-ggplot2
    - r-hmisc
    - r-mclust
    - r-seqinr
    - r-stringr
    - r-wmtsa
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The package provides an integrated pipeline for the analysis of PAR-CLIP data. PAR-CLIP-induced transitions are first discriminated from sequencing errors, SNPs and additional non-experimental sources by a non- parametric mixture model. The protein binding sites (clusters) are then resolved at high resolution and cluster statistics are estimated using a rigorous Bayesian framework. Post-processing of the results, data export for UCSC genome browser visualization and motif search analysis are provided. In addition, the package allows to integrate RNA-Seq data to estimate the False Discovery Rate of cluster detection. Key functions support parallel multicore computing. Note: while wavClusteR was designed for PAR-CLIP data analysis, it can be applied to the analysis of other NGS data obtained from experimental procedures that induce nucleotide substitutions (e.g. BisSeq).'

