{% set version = "1.18.0" %}
{% set name = "BEAT" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 687556436e352a09f1c1b944d5e783bf30da8ed2badbae4d0401534844e6199d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomicranges
    - bioconductor-shortread
    - r-base
  run:
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-genomicranges
    - bioconductor-shortread
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 3.0)'
  summary: 'Model-based analysis of single-cell methylation data'

