{% set version = "1.6.3" %}
{% set name = "recount" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 1ab27e802bfae64af83cd10d97c40bee50fa3eb97184e627b018778d81d1907c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocparallel
    - bioconductor-derfinder
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-geoquery
    - bioconductor-iranges
    - 'bioconductor-rtracklayer >=1.35.3'
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-downloader
    - r-rcurl
    - r-rentrez
  run:
    - bioconductor-biocparallel
    - bioconductor-derfinder
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-geoquery
    - bioconductor-iranges
    - 'bioconductor-rtracklayer >=1.35.3'
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-downloader
    - r-rcurl
    - r-rentrez
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Explore and download data from the recount project available at https://jhubiostatistics.shinyapps.io/recount/. Using the recount package you can download RangedSummarizedExperiment objects at the gene, exon or exon-exon junctions level, the raw counts, the phenotype metadata used, the urls to the sample coverage bigWig files or the mean coverage bigWig file for a particular study. The RangedSummarizedExperiment objects can be used by different packages for performing differential expression analysis. Using http://bioconductor.org/packages/derfinder you can perform annotation-agnostic differential expression analyses with the data from the recount project as described at http://www.nature.com/nbt/journal/v35/n4/full/nbt.3838.html.'

