{% set version = "1.16.1" %}
{% set name = "trackViewer" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 42d8d513d099d29764505ae646148b5954cc8cde5837e01af89a1970bba5eead
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-gviz
    - bioconductor-interactionset
    - bioconductor-iranges
    - bioconductor-rgraphviz
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - r-base
    - r-grimport
    - r-htmlwidgets
    - r-plotrix
    - r-scales
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-gviz
    - bioconductor-interactionset
    - bioconductor-iranges
    - bioconductor-rgraphviz
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - r-base
    - r-grimport
    - r-htmlwidgets
    - r-plotrix
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Visualize mapped reads along with annotation as track layers for NGS dataset such as ChIP-seq, RNA-seq, miRNA-seq, DNA-seq, SNPs and methylation data.'

