{% set version = "1.34.0" %}
{% set name = "tigre" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ce2d3f680a61019347c94d83e6f35826ee208505eaef7bd1faf72bca6e2b0a4b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - r-base
    - r-dbi
    - r-gplots
    - r-rsqlite
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - r-base
    - r-dbi
    - r-gplots
    - r-rsqlite
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: AGPL-3
  summary: 'The tigre package implements our methodology of Gaussian process differential equation models for analysis of gene expression time series from single input motif networks. The package can be used for inferring unobserved transcription factor (TF) protein concentrations from expression measurements of known target genes, or for ranking candidate targets of a TF.'

