{% set version = "2.22.0" %}
{% set name = "DrugVsDisease" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: cd1554211afe42f7f75549bdc331ff8a80a26d52acf4e4e3afde1d328f0c2d38
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-annotate
    - bioconductor-arrayexpress
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-cmap2data
    - bioconductor-drugvsdiseasedata
    - bioconductor-geoquery
    - bioconductor-hgu133a.db
    - bioconductor-hgu133a2.db
    - bioconductor-hgu133plus2.db
    - bioconductor-limma
    - bioconductor-qvalue
    - r-base
    - r-runit
    - r-xtable
  run:
    - bioconductor-affy
    - bioconductor-annotate
    - bioconductor-arrayexpress
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-cmap2data
    - bioconductor-drugvsdiseasedata
    - bioconductor-geoquery
    - bioconductor-hgu133a.db
    - bioconductor-hgu133a2.db
    - bioconductor-hgu133plus2.db
    - bioconductor-limma
    - bioconductor-qvalue
    - r-base
    - r-runit
    - r-xtable
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package generates ranked lists of differential gene expression for either disease or drug profiles. Input data can be downloaded from Array Express or GEO, or from local CEL files. Ranked lists of differential expression and associated p-values are calculated using Limma. Enrichment scores (Subramanian et al. PNAS 2005) are calculated to a reference set of default drug or disease profiles, or a set of custom data supplied by the user. Network visualisation of significant scores are output in Cytoscape format.'

