{% set version = "1.10.0" %}
{% set name = "mirIntegrator" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 69f2b51176831ce0ce2640c98c26d17520eb0c9d11838fef666218d35e8bf11b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-graph
    - bioconductor-org.hs.eg.db
    - bioconductor-rgraphviz
    - bioconductor-rontotools
    - r-base
    - r-ggplot2
  run:
    - bioconductor-annotationdbi
    - bioconductor-graph
    - bioconductor-org.hs.eg.db
    - bioconductor-rgraphviz
    - bioconductor-rontotools
    - r-base
    - r-ggplot2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=3)'
  summary: 'Tools for augmenting signaling pathways to perform pathway analysis of microRNA and mRNA expression levels.'

