{% set version = "1.52.0" %}
{% set name = "webbioc" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 89dee6b8f11fa13f49f128a629fa0dc101b3f9ffdfba186a533e4c4b943d697c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-annaffy
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - bioconductor-gcrma
    - bioconductor-multtest
    - bioconductor-qvalue
    - bioconductor-vsn
    - r-base
  run:
    - bioconductor-affy
    - bioconductor-annaffy
    - bioconductor-biobase
    - bioconductor-biocinstaller
    - bioconductor-gcrma
    - bioconductor-multtest
    - bioconductor-qvalue
    - bioconductor-vsn
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'An integrated web interface for doing microarray analysis using several of the Bioconductor packages. It is intended to be deployed as a centralized bioinformatics resource for use by many users. (Currently only Affymetrix oligonucleotide analysis is supported.)'

