{% set version = '1.1.10' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-exomedepth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ExomeDepth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ExomeDepth/ExomeDepth_{{ version }}.tar.gz
  sha256: 2678ff4c4d024e08a843f08cb932707a11ce7274ab48bfc2632669ca930d8f86

build:
  merge_build_host: True  # [win]

  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-biostrings
    - r-genomicalignments
    - r-genomicranges >=1.23.0
    - r-iranges
    - r-rsamtools
    - r-vgam >=0.8.4
    - r-aod

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-biostrings
    - r-genomicalignments
    - r-genomicranges >=1.23.0
    - r-iranges
    - r-rsamtools
    - r-vgam >=0.8.4
    - r-aod

test:
  commands:

    - $R -e "library('ExomeDepth')"           # [not win]
    - "\"%R%\" -e \"library('ExomeDepth')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ExomeDepth
  license: GPL-3
  summary: Calls copy number variants (CNVs) from targeted sequence data, typically exome sequencing
    experiments designed to identify the genetic basis of Mendelian disorders.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
