{% set version = "1.12.0" %}
{% set name = "rgsepd" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ff51af7f5824f951b219c0b62ed0ca9d8c1fde7a47526885b55c498c14df72bd
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biomart
    - bioconductor-deseq2
    - bioconductor-go.db
    - 'bioconductor-goseq >=1.28'
    - bioconductor-org.hs.eg.db
    - bioconductor-summarizedexperiment
    - r-base
    - r-gplots
    - r-hash
  run:
    - bioconductor-annotationdbi
    - bioconductor-biomart
    - bioconductor-deseq2
    - bioconductor-go.db
    - 'bioconductor-goseq >=1.28'
    - bioconductor-org.hs.eg.db
    - bioconductor-summarizedexperiment
    - r-base
    - r-gplots
    - r-hash
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'R/GSEPD is a bioinformatics package for R to help disambiguate transcriptome samples (a matrix of RNA-Seq counts at RefSeq IDs) by automating differential expression (with DESeq2), then gene set enrichment (with GOSeq), and finally a N-dimensional projection to quantify in which ways each sample is like either treatment group.'

