{% set version = "1.16.0" %}
{% set name = "Rariant" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: da698f812d7a8bfac97043800a7f3f95eed9f7a8697b90cf3426ecc89f5517d9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-exomecopy
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-ggbio
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-somaticsignatures
    - bioconductor-variantannotation
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-reshape2
    - r-shiny
    - r-vgam
  run:
    - bioconductor-biocgenerics
    - bioconductor-exomecopy
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-ggbio
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-somaticsignatures
    - bioconductor-variantannotation
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-reshape2
    - r-shiny
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'The ''Rariant'' package identifies single nucleotide variants from sequencing data based on the difference of binomially distributed mismatch rates between matched samples.'

