{% set version = "1.6.0" %}
{% set name = "alpine" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 42372a9247cde09da3b466b26a11e73b30f44e555e08210a0dbab67fb33e337a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-iranges
    - bioconductor-rbgl
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-speedglm
    - r-stringr
  run:
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-iranges
    - bioconductor-rbgl
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-speedglm
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Fragment sequence bias modeling and correction for RNA-seq transcript abundance estimation.'

