{% set version = "1.32.0" %}
{% set name = "goseq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 54f464d3cb096722138bd3771cb123f8eaf9c8f00265109077998aa12a5aab76
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - 'bioconductor-genelendatabase >=1.9.2'
    - bioconductor-go.db
    - r-base
    - r-biasedurn
    - r-mgcv
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - 'bioconductor-genelendatabase >=1.9.2'
    - bioconductor-go.db
    - r-base
    - r-biasedurn
    - r-mgcv
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'Detects Gene Ontology and/or other user defined categories which are over/under represented in RNA-seq data'

