{% set version = "1.12.0" %}
{% set name = "pwOmics" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7288ed9d0e6102383e884ecedc23c64cd81ff881e29f30542ed2962747ecfe33
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-annotationhub
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-rbiopaxparser
    - bioconductor-stringdb
    - r-base
    - r-data.table
    - r-gplots
    - r-igraph
  run:
    - bioconductor-annotationdbi
    - bioconductor-annotationhub
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-genomicranges
    - bioconductor-graph
    - bioconductor-rbiopaxparser
    - bioconductor-stringdb
    - r-base
    - r-data.table
    - r-gplots
    - r-igraph
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'pwOmics performs pathway-based level-specific data comparison of matching omics data sets based on pre-analysed user-specified lists of differential genes/transcripts and phosphoproteins. A separate downstream analysis of phosphoproteomic data including pathway identification, transcription factor identification and target gene identification is opposed to the upstream analysis starting with gene or transcript information as basis for identification of upstream transcription factors and potential proteomic regulators. The cross-platform comparative analysis allows for comprehensive analysis of single time point experiments and time-series experiments by providing static and dynamic analysis tools for data integration. In addition, it provides functions to identify individual signaling axes based on data integration.'

