{% set version = "1.8.0" %}
{% set name = "epivizrStandalone" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ebd600132569c5c391c33f593379fc3cc5aff9c3a46cb256adda1d4a0a5eb47e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - 'bioconductor-epivizr >=2.3.6'
    - bioconductor-epivizrserver
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-s4vectors
    - r-base
    - r-git2r
  run:
    - bioconductor-biocgenerics
    - 'bioconductor-epivizr >=2.3.6'
    - bioconductor-epivizrserver
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-s4vectors
    - r-base
    - r-git2r
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'This package imports the epiviz visualization JavaScript app for genomic data interactive visualization. The ''epivizrServer'' package is used to provide a web server running completely within R. This standalone version allows to browse arbitrary genomes through genome annotations provided by Bioconductor packages.'

