{% set version = "1.38.0" %}
{% set name = "flowFP" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 13eb62a9485c55e63c4fa957c86046872957cbcc8e01224f26c9165ebe2a5533
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.6'
    - bioconductor-flowcore
    - bioconductor-flowviz
    - r-base
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.6'
    - bioconductor-flowcore
    - bioconductor-flowviz
    - r-base
  build:
    - {{ compiler('c') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Fingerprint generation of flow cytometry data, used to facilitate the application of machine learning and datamining tools for flow cytometry.'

