{% set version = "2.16.0" %}
{% set name = "easyRNASeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 08fda441093ae8770cab7e4378fdcf6b5823e3689b9bbf5121acc0c6201d25c0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=2.39.1'
    - 'bioconductor-biocgenerics >=0.25.1'
    - 'bioconductor-biocparallel >=1.13.1'
    - 'bioconductor-biomart >=2.35.8'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-deseq >=1.31.0'
    - 'bioconductor-edger >=3.21.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomeintervals >=1.35.1'
    - 'bioconductor-genomicalignments >=1.15.6'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.13'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-shortread >=1.37.1'
    - 'bioconductor-summarizedexperiment >=1.9.9'
    - r-base
    - r-locfit
    - 'r-lsd >=3.0'
  run:
    - 'bioconductor-biobase >=2.39.1'
    - 'bioconductor-biocgenerics >=0.25.1'
    - 'bioconductor-biocparallel >=1.13.1'
    - 'bioconductor-biomart >=2.35.8'
    - 'bioconductor-biostrings >=2.47.6'
    - 'bioconductor-deseq >=1.31.0'
    - 'bioconductor-edger >=3.21.6'
    - 'bioconductor-genomeinfodb >=1.15.2'
    - 'bioconductor-genomeintervals >=1.35.1'
    - 'bioconductor-genomicalignments >=1.15.6'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.13'
    - 'bioconductor-rsamtools >=1.31.2'
    - 'bioconductor-s4vectors >=0.17.25'
    - 'bioconductor-shortread >=1.37.1'
    - 'bioconductor-summarizedexperiment >=1.9.9'
    - r-base
    - r-locfit
    - 'r-lsd >=3.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Calculates the coverage of high-throughput short-reads against a genome of reference and summarizes it per feature of interest (e.g. exon, gene, transcript). The data can be normalized as ''RPKM'' or by the ''DESeq'' or ''edgeR'' package.'

