{% set version = "1.26.0" %}
{% set name = "Repitools" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: cc74a0f353877f2ddb9f013fd969dec74fa0f9605701c96c159248704e653932
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.8.0'
    - bioconductor-biostrings
    - 'bioconductor-bsgenome >=1.47.3'
    - bioconductor-dnacopy
    - 'bioconductor-edger >=3.4.0'
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-ringo
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.17.25'
    - r-aroma.affymetrix
    - r-base
    - r-cluster
    - r-gplots
    - r-gsmoothr
    - r-mass
    - r-rsolnp
  run:
    - 'bioconductor-biocgenerics >=0.8.0'
    - bioconductor-biostrings
    - 'bioconductor-bsgenome >=1.47.3'
    - bioconductor-dnacopy
    - 'bioconductor-edger >=3.4.0'
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - 'bioconductor-iranges >=2.13.12'
    - bioconductor-ringo
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - 'bioconductor-s4vectors >=0.17.25'
    - r-aroma.affymetrix
    - r-base
    - r-cluster
    - r-gplots
    - r-gsmoothr
    - r-mass
    - r-rsolnp
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'Tools for the analysis of enrichment-based epigenomic data.  Features include summarization and visualization of epigenomic data across promoters according to gene expression context, finding regions of differential methylation/binding, BayMeth for quantifying methylation etc.'

