{% set version = "2.28.0" %}
{% set name = "GSRI" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 783e8a8d24ebe663da7e0a062ef4d6f6d01d1d7ef500223ea1a9d554dafe618b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-genefilter
    - bioconductor-gseabase
    - 'bioconductor-les >=1.1.6'
    - r-base
    - r-fdrtool
  run:
    - bioconductor-biobase
    - bioconductor-genefilter
    - bioconductor-gseabase
    - 'bioconductor-les >=1.1.6'
    - r-base
    - r-fdrtool
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'The GSRI package estimates the number of differentially expressed genes in gene sets, utilizing the concept of the Gene Set Regulation Index (GSRI).'

