{% set version = "1.38.0" %}
{% set name = "cghMCR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7a483c8f37fe841e4029634ffaa9a9fc502cd16824e98b037ad77ea60d057a75
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.1.6'
    - bioconductor-cntools
    - bioconductor-dnacopy
    - bioconductor-limma
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.1.6'
    - bioconductor-cntools
    - bioconductor-dnacopy
    - bioconductor-limma
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'This package provides functions to identify genomic regions of interests based on segmented copy number data from multiple samples.'

