{% set version = "2.54.0" %}
{% set name = "nem" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5a4fbc3eec8738bbfad002bb17a8a1e9d0263fe73441cc88fbbd7a70923c3910
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-graph
    - bioconductor-limma
    - 'bioconductor-rbgl >=1.8.1'
    - bioconductor-rgraphviz
    - r-base
    - r-boot
    - r-e1071
    - r-plotrix
    - r-rcolorbrewer
    - r-statmod
  run:
    - bioconductor-graph
    - bioconductor-limma
    - 'bioconductor-rbgl >=1.8.1'
    - bioconductor-rgraphviz
    - r-base
    - r-boot
    - r-e1071
    - r-plotrix
    - r-rcolorbrewer
    - r-statmod
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'The package ''nem'' allows to reconstruct features of pathways from the nested structure of perturbation effects. It takes as input (1.) a set of pathway components, which were perturbed, and (2.) phenotypic readout of these perturbations (e.g. gene expression, protein expression). The output is a directed graph representing the phenotypic hierarchy.'

