{% set version = "1.52.0" %}
{% set name = "annaffy" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a981787b7c682d2a65ef5001d2417038e401f24e3a8796b05c7ff33fcc376a72
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=0.1.15'
    - bioconductor-biobase
    - bioconductor-go.db
    - bioconductor-kegg.db
    - r-base
    - r-dbi
  run:
    - 'bioconductor-annotationdbi >=0.1.15'
    - bioconductor-biobase
    - bioconductor-go.db
    - bioconductor-kegg.db
    - r-base
    - r-dbi
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'Functions for handling data from Bioconductor Affymetrix annotation data packages. Produces compact HTML and text reports including experimental data and URL links to many online databases. Allows searching biological metadata using various criteria.'

