{% set version = "1.16.1" %}
{% set name = "STATegRa" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a86d2272b62d2a5d1bd50688d3eacbdd53d41a40ec5c19e9a74e6900d070e48a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-edger
    - bioconductor-limma
    - r-base
    - r-calibrate
    - r-foreach
    - r-ggplot2
    - r-gplots
    - r-gridextra
    - r-mass
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-edger
    - bioconductor-limma
    - r-base
    - r-calibrate
    - r-foreach
    - r-ggplot2
    - r-gplots
    - r-gridextra
    - r-mass
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Classes and tools for multi-omics data integration.'

