{% set version = "3.7.2" %}
{% set name = "phastCons100way.UCSC.hg19" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ca052a0f6e874bcc8079b29e3cc1a29cb6b852b32d5a7a45dea5cff7c924acca
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - 'bioconductor-genomicscores >=1.3.19'
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
  run:
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - 'bioconductor-genomicscores >=1.3.19'
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Store UCSC phastCons conservation scores for the human genome (hg19) calculated from multiple alignments with other 99 vertebrate species.'

