{% set version = "1.18.0" %}
{% set name = "maPredictDSC" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d632461eae6b5153f6962c09fece614f26bd1f93c3dabdc6432d5be4d457a363
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-annotationdbi
    - bioconductor-gcrma
    - bioconductor-hgu133plus2.db
    - bioconductor-limma
    - bioconductor-lungcanceracvssccgeo
    - bioconductor-roc
    - r-base
    - r-caret
    - r-class
    - r-e1071
    - r-mass
    - r-rocr
  run:
    - bioconductor-affy
    - bioconductor-annotationdbi
    - bioconductor-gcrma
    - bioconductor-hgu133plus2.db
    - bioconductor-limma
    - bioconductor-lungcanceracvssccgeo
    - bioconductor-roc
    - r-base
    - r-caret
    - r-class
    - r-e1071
    - r-mass
    - r-rocr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package implements the classification pipeline of the best overall team (Team221) in the IMPROVER Diagnostic Signature Challenge. Additional functionality is added to compare 27 combinations of data preprocessing, feature selection and classifier types.'

