{% set version = "1.2.0" %}
{% set name = "IsoformSwitchAnalyzeR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 21d5419ad3361793d6b39903f732bfbaffcf5bca7edae1ee2b969e75709d67fc
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-cummerbund
    - bioconductor-drimseq
    - bioconductor-edger
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - bioconductor-tximport
    - r-base
    - r-dbi
    - r-futile.logger
    - r-ggplot2
    - r-gridextra
    - r-plyr
    - r-rcolorbrewer
    - r-reshape2
    - r-venndiagram
  run:
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-cummerbund
    - bioconductor-drimseq
    - bioconductor-edger
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - bioconductor-tximport
    - r-base
    - r-dbi
    - r-futile.logger
    - r-ggplot2
    - r-gridextra
    - r-plyr
    - r-rcolorbrewer
    - r-reshape2
    - r-venndiagram
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'IsoformSwitchAnalyzeR enables identification and analysis of isoform switches with predicted functional consequences (such as gain/loss of protein domains etc) from quantification by Kallisto, Salmon, Cufflinks/Cuffdiff, RSEM etc.'

