{% set version = "2.56.0" %}
{% set name = "simpleaffy" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 66370f3b505208b22130c23e7e62aba8fb59e5a0441866536cfd28a5322d8f04
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affy >=1.33.6'
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.12'
    - bioconductor-gcrma
    - bioconductor-genefilter
    - r-base
  run:
    - 'bioconductor-affy >=1.33.6'
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.12'
    - bioconductor-gcrma
    - bioconductor-genefilter
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Provides high level functions for reading Affy .CEL files, phenotypic data, and then computing simple things with it, such as t-tests, fold changes and the like. Makes heavy use of the affy library. Also has some basic scatter plot functions and mechanisms for generating high resolution journal figures...'

