{% set version = "1.56.0" %}
{% set name = "makecdfenv" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2bd03184374ccde9683d2b614183918217f9364fa5b51035a67b34dac11d04b5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-affyio
    - bioconductor-biobase
    - bioconductor-zlibbioc
    - r-base
  run:
    - bioconductor-affy
    - bioconductor-affyio
    - bioconductor-biobase
    - bioconductor-zlibbioc
    - r-base
  build:
    - {{ compiler('c') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'This package has two functions. One reads a Affymetrix chip description file (CDF) and creates a hash table environment containing the location/probe set membership mapping. The other creates a package that automatically loads that environment.'

