{% set version = "2.42.0" %}
{% set name = "altcdfenvs" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ddba4b59069c284eea7b2ca54a9f1ed0c46dc514e64db4badeb43cdd5a4fea33
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - 'bioconductor-biobase >=2.15.1'
    - 'bioconductor-biocgenerics >=0.1.0'
    - bioconductor-biostrings
    - bioconductor-hypergraph
    - bioconductor-makecdfenv
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
  run:
    - bioconductor-affy
    - 'bioconductor-biobase >=2.15.1'
    - 'bioconductor-biocgenerics >=0.1.0'
    - bioconductor-biostrings
    - bioconductor-hypergraph
    - bioconductor-makecdfenv
    - 'bioconductor-s4vectors >=0.9.25'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Convenience data structures and functions to handle cdfenvs'

