{% set version = "1.12.0" %}
{% set name = "seqPattern" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7c5c0e62021cfeafa31682277e88aa343969650cfdd28eef5e1138e61af58037
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - r-base
    - r-kernsmooth
    - r-plotrix
  run:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - r-base
    - r-kernsmooth
    - r-plotrix
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Visualising oligonucleotide patterns and sequence motifs occurrences across a large set of sequences centred at a common reference point and sorted by a user defined feature.'

