{% set version = "1.38.0" %}
{% set name = "affyContam" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: afc3e450d15878232ad906959da83cd71b24516b35b86b718f37f600db78bd29
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - bioconductor-affydata
    - bioconductor-biobase
    - r-base
  run:
    - bioconductor-affy
    - bioconductor-affydata
    - bioconductor-biobase
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'structured corruption of cel file data to demonstrate QA effectiveness'

