{% set version = "1.24.0" %}
{% set name = "motifRG" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 3760c720798edbeae5ba2387bc293a1f949281f0c9bcd5a0c25f343f5bf4b057
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biostrings >=2.26'
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-iranges
    - bioconductor-seqlogo
    - bioconductor-xvector
    - r-base
  run:
    - 'bioconductor-biostrings >=2.26'
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-iranges
    - bioconductor-seqlogo
    - bioconductor-xvector
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Tools for discriminative motif discovery using regression methods'

