{% set version = "1.22.0" %}
{% set name = "chimera" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: b24054dd8cfccd9fcb5ae546a8b220c91eac68a8e965ddd1bd224ec3dfc16ccf
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-genomicalignments
    - 'bioconductor-genomicranges >=1.13.3'
    - bioconductor-homo.sapiens
    - 'bioconductor-rsamtools >=1.13.1'
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
    - r-base
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-genomicalignments
    - 'bioconductor-genomicranges >=1.13.3'
    - bioconductor-homo.sapiens
    - 'bioconductor-rsamtools >=1.13.1'
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
    - r-base
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package facilitates the characterisation of fusion products events. It allows to import fusion data results from the following fusion finders:  chimeraScan, bellerophontes, deFuse, FusionFinder, FusionHunter, mapSplice, tophat-fusion, FusionMap, STAR, Rsubread, fusionCatcher.'

