{% set version = "1.8.4" %}
{% set name = "scran" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: d288b0413d7235b40a71483e6dfbc97587f4474fd5f28b5925f64c95d64e789f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-beachmat
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-delayedarray
    - bioconductor-delayedmatrixstats
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-rhdf5lib
    - bioconductor-s4vectors
    - bioconductor-scater
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-base
    - r-dt
    - r-dynamictreecut
    - r-fnn
    - r-ggplot2
    - r-igraph
    - r-matrix
    - 'r-rcpp >=0.12.14'
    - r-shiny
    - r-statmod
    - r-viridis
  run:
    - bioconductor-beachmat
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-delayedarray
    - bioconductor-delayedmatrixstats
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-rhdf5lib
    - bioconductor-s4vectors
    - bioconductor-scater
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-base
    - r-dt
    - r-dynamictreecut
    - r-fnn
    - r-ggplot2
    - r-igraph
    - r-matrix
    - 'r-rcpp >=0.12.14'
    - r-shiny
    - r-statmod
    - r-viridis
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Implements functions for low-level analyses of single-cell RNA-seq data. Methods are provided for normalization of cell-specific biases, assignment of cell cycle phase, detection of highly variable and significantly correlated genes, correction of batch effects, identification of marker genes, and other common tasks in single-cell analysis workflows.'

