{% set version = "3.36.0" %}
{% set name = "arrayQualityMetrics" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d31f0bea123391dd118e7d91e8a8074a40e2ca6c32631062b4ea81dd35ffcd5e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - 'bioconductor-affyplm >=1.27.3'
    - bioconductor-beadarray
    - bioconductor-biobase
    - bioconductor-genefilter
    - bioconductor-limma
    - 'bioconductor-vsn >=3.23.3'
    - r-base
    - 'r-cairo >=1.4-6'
    - 'r-gridsvg >=1.4-3'
    - r-hmisc
    - r-hwriter
    - r-lattice
    - r-latticeextra
    - r-rcolorbrewer
    - r-setrng
    - r-xml
  run:
    - bioconductor-affy
    - 'bioconductor-affyplm >=1.27.3'
    - bioconductor-beadarray
    - bioconductor-biobase
    - bioconductor-genefilter
    - bioconductor-limma
    - 'bioconductor-vsn >=3.23.3'
    - r-base
    - 'r-cairo >=1.4-6'
    - 'r-gridsvg >=1.4-3'
    - r-hmisc
    - r-hwriter
    - r-lattice
    - r-latticeextra
    - r-rcolorbrewer
    - r-setrng
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'This package generates microarray quality metrics reports for data in Bioconductor microarray data containers (ExpressionSet, NChannelSet, AffyBatch). One and two color array platforms are supported.'

