{% set version = "1.28.0" %}
{% set name = "a4Base" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ed117190a960d4e69725cf5fd1f2c7c785a5258c06eb897d80f0a57626ae7520
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-a4core
    - bioconductor-a4preproc
    - bioconductor-annaffy
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-genefilter
    - bioconductor-limma
    - bioconductor-multtest
    - r-base
    - r-glmnet
    - r-gplots
    - r-mpm
  run:
    - bioconductor-a4core
    - bioconductor-a4preproc
    - bioconductor-annaffy
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-genefilter
    - bioconductor-limma
    - bioconductor-multtest
    - r-base
    - r-glmnet
    - r-gplots
    - r-mpm
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Automated Affymetrix Array Analysis'

