{% set version = "1.26.1" %}
{% set name = "deepSNV" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 55036b553920826aeead816e48a8760b756bca513de09a247521b36788aaa01d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.13.44'
    - r-base
    - r-vgam
  run:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-summarizedexperiment
    - 'bioconductor-variantannotation >=1.13.44'
    - r-base
    - r-vgam
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package provides provides quantitative variant callers for detecting subclonal mutations in ultra-deep (>=100x coverage) sequencing experiments. The deepSNV algorithm is used for a comparative setup with a control experiment of the same loci and uses a beta-binomial model and a likelihood ratio test to discriminate sequencing errors and subclonal SNVs. The shearwater algorithm computes a Bayes classifier based on a beta-binomial model for variant calling with multiple samples for precisely estimating model parameters - such as local error rates and dispersion - and prior knowledge, e.g. from variation data bases such as COSMIC.'

