{% set version = "1.26.0" %}
{% set name = "CellNOptR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1eb26216d20f4a4a6824b4bea4c328c794143280c51a5eb4e5251033d708776f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
    - r-ggplot2
    - r-hash
    - r-rcurl
    - r-xml
  run:
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
    - r-ggplot2
    - r-hash
    - r-rcurl
    - r-xml
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package does optimisation of boolean logic networks of signalling pathways based on a previous knowledge network and a set of data upon perturbation of the nodes in the network.'

