{% set version = "1.12.1" %}
{% set name = "bamsignals" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: fb552c89b77193ab47eba93c1cfd03547645100e18c5ee6a9838f24fc91d3890
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-zlibbioc
    - r-base
    - 'r-rcpp >=0.10.6'
  run:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-zlibbioc
    - r-base
    - 'r-rcpp >=0.10.6'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package allows to efficiently obtain count vectors from indexed bam files. It counts the number of reads in given genomic ranges and it computes reads profiles and coverage profiles. It also handles paired-end data.'

