{% set version = "1.24.0" %}
{% set name = "wateRmelon" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 01a311de4db43001c9fa0f2695fe6737aee266f67672dcd5fa3dab9f9ddc2db4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
    - bioconductor-illuminaio
    - bioconductor-limma
    - bioconductor-lumi
    - bioconductor-methylumi
    - bioconductor-roc
    - r-base
    - r-matrixstats
  run:
    - bioconductor-biobase
    - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
    - bioconductor-illuminaio
    - bioconductor-limma
    - bioconductor-lumi
    - bioconductor-methylumi
    - bioconductor-roc
    - r-base
    - r-matrixstats
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: '15 flavours of betas and three performance metrics, with methods for objects produced by methylumi and minfi packages.'

