{% set version = "1.10.0" %}
{% set name = "TarSeqQC" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e2d70634d99666fec6b80209bb8cfdef7a35f76ddfbfd806751d70e74aad9047
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.20.4'
    - bioconductor-s4vectors
    - r-base
    - r-cowplot
    - r-ggplot2
    - r-hmisc
    - r-openxlsx
    - r-plyr
    - r-reshape2
  run:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-rsamtools >=1.20.4'
    - bioconductor-s4vectors
    - r-base
    - r-cowplot
    - r-ggplot2
    - r-hmisc
    - r-openxlsx
    - r-plyr
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'The package allows the representation of targeted experiment in R. This is based on current packages and incorporates functions to do a quality control over this kind of experiments and a fast exploration of the sequenced regions. An xlsx file is generated as output.'

