{% set version = "3.28.2" %}
{% set name = "flowWorkspace" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 64f60df146a17b9ef0f4935a3db3fcabc31820aa4da61fc7408fb1c0d19a46a8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-cytolib >=1.1.3'
    - 'bioconductor-flowcore >=1.45.14'
    - bioconductor-flowviz
    - bioconductor-graph
    - 'bioconductor-ncdfflow >=2.25.4'
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - bioconductor-rprotobuflib
    - r-base
    - 'r-bh >=1.62.0-1'
    - r-data.table
    - r-dplyr
    - r-gridextra
    - r-lattice
    - r-latticeextra
    - r-matrixstats
    - r-rcolorbrewer
    - r-rcpp
    - r-scales
    - r-stringr
    - r-xml
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-cytolib >=1.1.3'
    - 'bioconductor-flowcore >=1.45.14'
    - bioconductor-flowviz
    - bioconductor-graph
    - 'bioconductor-ncdfflow >=2.25.4'
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - bioconductor-rprotobuflib
    - r-base
    - 'r-bh >=1.62.0-1'
    - r-data.table
    - r-dplyr
    - r-gridextra
    - r-lattice
    - r-latticeextra
    - r-matrixstats
    - r-rcolorbrewer
    - r-rcpp
    - r-scales
    - r-stringr
    - r-xml
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package is designed to facilitate comparison of automated gating methods against manual gating done in flowJo. This package allows you to import basic flowJo workspaces into BioConductor and replicate the gating from flowJo using the flowCore functionality. Gating hierarchies, groups of samples, compensation, and transformation are performed so that the output matches the flowJo analysis.'

