{% set version = "2.6.4" %}
{% set name = "MSnbase" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 35872e6a5057deb33ff46bb544c0c15c781f6ae15f3551b437b6b41c166a3bb2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-affy
    - 'bioconductor-biobase >=2.15.2'
    - 'bioconductor-biocgenerics >=0.7.1'
    - bioconductor-biocparallel
    - bioconductor-impute
    - 'bioconductor-iranges >=2.13.28'
    - 'bioconductor-mzid >=1.5.2'
    - 'bioconductor-mzr >=2.13.6'
    - bioconductor-pcamethods
    - bioconductor-preprocesscore
    - 'bioconductor-protgenerics >=1.9.1'
    - bioconductor-s4vectors
    - bioconductor-vsn
    - r-base
    - r-digest
    - r-ggplot2
    - r-lattice
    - 'r-maldiquant >=1.16'
    - r-mass
    - r-plyr
    - r-rcpp
    - r-scales
    - r-xml
  run:
    - bioconductor-affy
    - 'bioconductor-biobase >=2.15.2'
    - 'bioconductor-biocgenerics >=0.7.1'
    - bioconductor-biocparallel
    - bioconductor-impute
    - 'bioconductor-iranges >=2.13.28'
    - 'bioconductor-mzid >=1.5.2'
    - 'bioconductor-mzr >=2.13.6'
    - bioconductor-pcamethods
    - bioconductor-preprocesscore
    - 'bioconductor-protgenerics >=1.9.1'
    - bioconductor-s4vectors
    - bioconductor-vsn
    - r-base
    - r-digest
    - r-ggplot2
    - r-lattice
    - 'r-maldiquant >=1.16'
    - r-mass
    - r-plyr
    - r-rcpp
    - r-scales
    - r-xml
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'MSnbase provides infrastructure for manipulation, processing and visualisation of mass spectrometry and proteomics data, ranging from raw to quantitative and annotated data.'

