{% set version = "1.32.0" %}
{% set name = "hyperdraw" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ecc1fc2a682b262eb72d80d8ace1159c1a1a8c99a7fa93c63c3dae2bb75e8ece
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-graph
    - bioconductor-hypergraph
    - bioconductor-rgraphviz
    - r-base
  run:
    - bioconductor-graph
    - bioconductor-hypergraph
    - bioconductor-rgraphviz
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Functions for visualizing hypergraphs.'

