{% set version = "1.2.1" %}
{% set name = "scPipe" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ae2c9d2c00b750e95fbf735e031bfc0055568a9c6506db1cbb38083ac0e5d89a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - bioconductor-zlibbioc
    - r-base
    - r-ggally
    - r-ggplot2
    - r-mass
    - r-mclust
    - 'r-rcpp >=0.11.3'
    - r-reshape
    - r-robustbase
    - r-scales
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - 'bioconductor-rhtslib >=1.12.1'
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - bioconductor-zlibbioc
    - r-base
    - r-ggally
    - r-ggplot2
    - r-mass
    - r-mclust
    - 'r-rcpp >=0.11.3'
    - r-reshape
    - r-robustbase
    - r-scales
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'A preprocessing pipeline for single cell RNA-seq data that starts from the fastq files and produces a gene count matrix with associated quality control information. It can process fastq data generated by CEL-seq, MARS-seq, Drop-seq, Chromium 10x and SMART-seq protocols.'

