{% set version = "0.20.0" %}
{% set name = "XVector" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 6e5c1a3b9f5ff1319082165bdc7e5e33a121b8d70c1514b4040f7a4d138454fe
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.19.2'
    - 'bioconductor-iranges >=2.13.16'
    - 'bioconductor-s4vectors >=0.17.24'
    - bioconductor-zlibbioc
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.19.2'
    - 'bioconductor-iranges >=2.13.16'
    - 'bioconductor-s4vectors >=0.17.24'
    - bioconductor-zlibbioc
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Memory efficient S4 classes for storing sequences "externally" (behind an R external pointer, or on disk).'

