{% set version = "1.16.1" %}
{% set name = "ChIPQC" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: fdebb0fdc165e292b0141a2f540f6bb24c112202b0b8a6a4bed41394e9687abc
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.11.3'
    - bioconductor-biocparallel
    - 'bioconductor-chipseq >=1.12.0'
    - bioconductor-diffbind
    - 'bioconductor-genomicalignments >=1.1.16'
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.17.19'
    - 'bioconductor-iranges >=1.99.17'
    - 'bioconductor-rsamtools >=1.17.28'
    - 'bioconductor-s4vectors >=0.1.0'
    - bioconductor-txdb.celegans.ucsc.ce6.ensgene
    - bioconductor-txdb.dmelanogaster.ucsc.dm3.ensgene
    - bioconductor-txdb.hsapiens.ucsc.hg18.knowngene
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
    - bioconductor-txdb.mmusculus.ucsc.mm10.knowngene
    - bioconductor-txdb.mmusculus.ucsc.mm9.knowngene
    - bioconductor-txdb.rnorvegicus.ucsc.rn4.ensgene
    - r-base
    - r-ggplot2
    - r-gtools
    - r-nozzle.r1
    - r-reshape2
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.11.3'
    - bioconductor-biocparallel
    - 'bioconductor-chipseq >=1.12.0'
    - bioconductor-diffbind
    - 'bioconductor-genomicalignments >=1.1.16'
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.17.19'
    - 'bioconductor-iranges >=1.99.17'
    - 'bioconductor-rsamtools >=1.17.28'
    - 'bioconductor-s4vectors >=0.1.0'
    - bioconductor-txdb.celegans.ucsc.ce6.ensgene
    - bioconductor-txdb.dmelanogaster.ucsc.dm3.ensgene
    - bioconductor-txdb.hsapiens.ucsc.hg18.knowngene
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
    - bioconductor-txdb.mmusculus.ucsc.mm10.knowngene
    - bioconductor-txdb.mmusculus.ucsc.mm9.knowngene
    - bioconductor-txdb.rnorvegicus.ucsc.rn4.ensgene
    - r-base
    - r-ggplot2
    - r-gtools
    - r-nozzle.r1
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'Quality metrics for ChIPseq data.'

