{% set version = "2.22.0" %}
{% set name = "ExiMiR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8db4a380e83229f0c0604eca519026a9744e64b89aa01080a9349f1cec553c68
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affy >=1.26.1'
    - 'bioconductor-affyio >=1.13.3'
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-limma
    - 'bioconductor-preprocesscore >=1.10.0'
    - r-base
  run:
    - 'bioconductor-affy >=1.26.1'
    - 'bioconductor-affyio >=1.13.3'
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-limma
    - 'bioconductor-preprocesscore >=1.10.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package contains functions for reading raw data in ImaGene TXT format obtained from Exiqon miRCURY LNA arrays, annotating them with appropriate GAL files, and normalizing them using a spike-in probe-based method. Other platforms and data formats are also supported.'

