{% set version = "2.26.0" %}
{% set name = "methylumi" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 57c7dd21135f97eb787d09ed8807eb5c5971b0c43dd55627208d9b0256ab662d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-fdb.infiniummethylation.hg19 >=2.2.0'
    - bioconductor-genefilter
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-minfi
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-ggplot2
    - r-lattice
    - r-matrixstats
    - r-reshape2
    - r-scales
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'bioconductor-fdb.infiniummethylation.hg19 >=2.2.0'
    - bioconductor-genefilter
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-illuminaio
    - bioconductor-iranges
    - bioconductor-minfi
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-ggplot2
    - r-lattice
    - r-matrixstats
    - r-reshape2
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package provides classes for holding and manipulating Illumina methylation data.  Based on eSet, it can contain MIAME information, sample information, feature information, and multiple matrices of data.  An "intelligent" import function, methylumiR can read the Illumina text files and create a MethyLumiSet. methylumIDAT can directly read raw IDAT files from HumanMethylation27 and HumanMethylation450 microarrays.  Normalization, background correction, and quality control features for GoldenGate, Infinium, and Infinium HD arrays are also included.'

