{% set version = "1.48.3" %}
{% set name = "biocViews" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 6582f5a443e33bc33ba584e7021d3564fcd791ff9a7ec5a4ec4fef8867e4bbe7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-graph >=1.9.26'
    - 'bioconductor-rbgl >=1.13.5'
    - r-base
    - r-rcurl
    - r-runit
    - r-xml
  run:
    - bioconductor-biobase
    - 'bioconductor-graph >=1.9.26'
    - 'bioconductor-rbgl >=1.13.5'
    - r-base
    - r-rcurl
    - r-runit
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Infrastructure to support Bioconductor ''views'' used to classify software packages. ''biocViews'' are directed acyclic graphs of terms from a controlled vocabulary. There are three major classifications, corresponding to ''software'', ''annotation'', and ''experiment data'' packages.'

