{% set version = "2.44.0" %}
{% set name = "cellHTS2" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 90c46478b3a0e3e3b812b20c311cf41899bb94965e30820bb174e15904548a4a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-category
    - bioconductor-genefilter
    - bioconductor-gseabase
    - bioconductor-prada
    - bioconductor-splots
    - bioconductor-vsn
    - r-base
    - r-hwriter
    - r-locfit
    - r-rcolorbrewer
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-category
    - bioconductor-genefilter
    - bioconductor-gseabase
    - bioconductor-prada
    - bioconductor-splots
    - bioconductor-vsn
    - r-base
    - r-hwriter
    - r-locfit
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package provides tools for the analysis of high-throughput assays that were performed in microtitre plate formats (including but not limited to 384-well plates). The functionality includes data import and management, normalisation, quality assessment, replicate summarisation and statistical scoring. A webpage that provides a detailed graphical overview over the data and analysis results is produced. In our work, we have applied the package to RNAi screens on fly and human cells, and for screens of yeast libraries. See ?cellHTS2 for a brief introduction.'

