{% set version = "1.10.1" %}
{% set name = "SummarizedExperiment" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 81dacf10280d5f6e79a5eed84c1ccaac7cf536a47f5b569e4a676bcc12ed7f6c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.15.3'
    - 'bioconductor-delayedarray >=0.3.20'
    - 'bioconductor-genomeinfodb >=1.13.1'
    - 'bioconductor-genomicranges >=1.31.17'
    - 'bioconductor-iranges >=2.13.16'
    - 'bioconductor-s4vectors >=0.17.25'
    - r-base
    - r-matrix
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.15.3'
    - 'bioconductor-delayedarray >=0.3.20'
    - 'bioconductor-genomeinfodb >=1.13.1'
    - 'bioconductor-genomicranges >=1.31.17'
    - 'bioconductor-iranges >=2.13.16'
    - 'bioconductor-s4vectors >=0.17.25'
    - r-base
    - r-matrix
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'The SummarizedExperiment container contains one or more assays, each represented by a matrix-like object of numeric or other mode. The rows typically represent genomic ranges of interest and the columns represent samples.'

