{% set version = "1.40.0" %}
{% set name = "flowQ" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: dd8c8464e300c02001e731140d3c86f828e4acdf2aab7dd58f8abbd3f52d0ac4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biocgenerics
    - bioconductor-biodist
    - bioconductor-flowcore
    - bioconductor-flowviz
    - bioconductor-geneplotter
    - bioconductor-iranges
    - bioconductor-parody
    - r-base
    - r-lattice
    - r-latticeextra
    - r-mvoutlier
    - r-outliers
    - r-rcolorbrewer
  run:
    - bioconductor-biocgenerics
    - bioconductor-biodist
    - bioconductor-flowcore
    - bioconductor-flowviz
    - bioconductor-geneplotter
    - bioconductor-iranges
    - bioconductor-parody
    - r-base
    - r-lattice
    - r-latticeextra
    - r-mvoutlier
    - r-outliers
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Provides quality control and quality assessment tools for flow cytometry data.'

