{% set version = "1.20.0" %}
{% set name = "DESeq2" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 33e214e9f9f9bb5d6c0dacdd0d4a8ba4857ce0277f09a192ab35a940d67556f2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-biocparallel
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
    - r-ggplot2
    - r-hmisc
    - r-locfit
    - 'r-rcpp >=0.11.0'
    - r-rcpparmadillo
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-biocparallel
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
    - r-ggplot2
    - r-hmisc
    - r-locfit
    - 'r-rcpp >=0.11.0'
    - r-rcpparmadillo
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 3)'
  summary: 'Estimate variance-mean dependence in count data from high-throughput sequencing assays and test for differential expression based on a model using the negative binomial distribution.'

