{% set version = "1.30.0" %}
{% set name = "chipseq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a767466f1511d1d3682a7a8ed5c9a6f7e63832bf776f7bdcc4e5445be86bc825
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.1.0'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-s4vectors >=0.17.25'
    - bioconductor-shortread
    - r-base
    - r-lattice
  run:
    - 'bioconductor-biocgenerics >=0.1.0'
    - 'bioconductor-genomicranges >=1.31.8'
    - 'bioconductor-iranges >=2.13.12'
    - 'bioconductor-s4vectors >=0.17.25'
    - bioconductor-shortread
    - r-base
    - r-lattice
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Tools for helping process short read data for chipseq experiments'

