{% set version = "2.10.0" %}
{% set name = "RTCGAToolbox" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 34cc165a907c64898dd096234155b946d6ff87a097c1cc0b65eb68856ee573b8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-limma >=3.18'
    - bioconductor-raggedexperiment
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - 'r-data.table >=1.9.4'
    - r-httr
    - r-plyr
    - r-rcircos
    - r-rcurl
    - r-rjsonio
    - r-stringr
    - r-survival
    - r-xml
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-limma >=3.18'
    - bioconductor-raggedexperiment
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - 'r-data.table >=1.9.4'
    - r-httr
    - r-plyr
    - r-rcircos
    - r-rcurl
    - r-rjsonio
    - r-stringr
    - r-survival
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'file LICENSE'
  summary: 'Managing data from large scale projects such as The Cancer Genome Atlas (TCGA) for further analysis is an important and time consuming step for research projects. Several efforts, such as Firehose project, make TCGA pre-processed data publicly available via web services and data portals but it requires managing, downloading and preparing the data for following steps. We developed an open source and extensible R based data client for Firehose pre-processed data and demonstrated its use with sample case studies. Results showed that RTCGAToolbox could improve data management for researchers who are interested with TCGA data. In addition, it can be integrated with other analysis pipelines for following data analysis.'

