{% set version = "1.26.0" %}
{% set name = "DEXSeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e1e9026c07fc26e1eaee06a0dd63d2f765bcd711f350fdb2a2236ad65b1d0bd7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biomart
    - 'bioconductor-deseq2 >=1.9.11'
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - 'bioconductor-genomicranges >=1.23.7'
    - 'bioconductor-iranges >=2.5.17'
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-hwriter
    - r-rcolorbrewer
    - r-statmod
    - r-stringr
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biomart
    - 'bioconductor-deseq2 >=1.9.11'
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - 'bioconductor-genomicranges >=1.23.7'
    - 'bioconductor-iranges >=2.5.17'
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
    - r-hwriter
    - r-rcolorbrewer
    - r-statmod
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'The package is focused on finding differential exon usage using RNA-seq exon counts between samples with different experimental designs. It provides functions that allows the user to make the necessary statistical tests based on a model that uses the negative binomial distribution to estimate the variance between biological replicates and generalized linear models for testing. The package also provides functions for the visualization and exploration of the results.'

