{% set version = "2.26.0" %}
{% set name = "SNPchip" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 9b28bd2c43d69308e4bb02714f877614d67e562384f48029b56ad22cf6e3a30a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-oligoclasses >=1.31.1'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - r-base
    - r-foreach
    - r-lattice
  run:
    - bioconductor-biobase
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-oligoclasses >=1.31.1'
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - r-base
    - r-foreach
    - r-lattice
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'Functions for plotting SNP array data; maintained for historical reasons'

