{% set version = "1.20.3" %}
{% set name = "MLSeq" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 09663f7b24051519e3f587c95a35122a4f571907ec1a93db0b40d9b7e119f26d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-deseq2
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-sseq
    - bioconductor-summarizedexperiment
    - r-base
    - r-caret
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-xtable
  run:
    - bioconductor-biobase
    - bioconductor-deseq2
    - bioconductor-edger
    - bioconductor-limma
    - bioconductor-sseq
    - bioconductor-summarizedexperiment
    - r-base
    - r-caret
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-xtable
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL(>=2)
  summary: 'This package applies several machine learning methods, including SVM, bagSVM, Random Forest and CART to RNA-Seq data.'

